#!/bin/sh
# MAINTAINER: Piotr Simon 'sjn' <sajmon@tenboard.com>
# SOURCES: http://downloads.sourceforge.net/kipi/libkipi-0.1.5.tar.bz2
# MD5SUMS: 395d87ad36b1261f58bdeac87145734c libkipi-0.1.1.tar.bz2
# MD5SUMS: aef790871583444cd81bd9dea9c3fd0b libkipi-0.1.5.tar.bz2
# REQUIRES: kdelibs
# OPTIONAL: desktop-file-utils
VERSION=0.1.5
ARCH=${ARCH:-i486}
BUILD=1sjn

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME
rm -rf $PKG
mkdir -p $PKG/{install,usr/doc/$NAME-$VERSION}

cd $TMP || exit 1
tar xjvf $CWD/$NAME-$VERSION.tar.bz2 || exit 1
cd $NAME-$VERSION || exit 1
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  --disable-static \
  $ARCH-slackware-linux || exit 1
make || exit 1
make install DESTDIR=$PKG || exit 1
cp -a \
  AUTHORS ChangeLog COPYING INSTALL README TODO VERSION \
  $PKG/usr/doc/$NAME-$VERSION/

cd $PKG || exit 1
cat $CWD/slack-desc >$PKG/install/slack-desc

find -type d | grep /doc/ | xargs -r chmod 755
find -type f | grep /doc/ | xargs -r chmod 644
find -type f | xargs file | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
find -type f | grep -e /man/ -e /info/ | xargs -r gzip -9

makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/libkipi-$VERSION
  rm -rf $PKG
fi
