#!/bin/sh
# MAINTAINER: Piotr Simon 'sjn' <sajmon@tenboard.com>
# SOURCES: http://heanet.dl.sourceforge.net/sourceforge/sylpheed-claws/sylpheed-claws-2.3.1.tar.bz2
# MD5SUMS: 08e8fe1f3466d146b499d128f1445ba6  sylpheed-claws-2.3.1.tar.bz2
# MD5SUMS: a59b1f1736e89918c648794c94120a8e  sylpheed-claws-2.3.0.tar.bz2
# MD5SUMS: 870eb4de8dc242f16171145d8af725b9  sylpheed-claws-2.2.3.tar.bz2
# MD5SUMS: 4a047d028327c0e7b3ef0b058bd62d91  sylpheed-claws-2.2.0.tar.bz2
# MD5SUMS: 8d7b1d01c4f236a5e7d3e139bf43cd5a  sylpheed-claws-2.1.1.tar.bz2
# MD5SUMS: 6e26f8e36772b71361d0c463b9a6c7a1  sylpheed-claws-2.0.0.tar.bz2
# MD5SUMS: ac473de7189a4a9baecf16b72c34dff4  sylpheed-claws-1.0.4.tar.bz2
# REQUIRES: aspell cxxlibs gdk-pixbuf glib gpgme gtk+ openssl startup-notification x11 x11-devel
# OPTIONAL: cyrus-sasl db4 expat glib2 glibc gtk+2 libetpan libgpg-error libpng openldap-client zlib
TMP=${TMP:-/var/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.3.1
ARCH=${ARCH:-i486}
BUILD=1sjn

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG $TMP/$NAME-$VERSION
mkdir -p $PKG/usr
cd $TMP || exit 1
tar xjvf $CWD/$NAME-$VERSION.tar.bz2 || exit 1
cd $NAME-$VERSION || exit 1
zcat $CWD/sylpheed-claws-gettext.patch.gz | patch -p1 || exit 1

chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --enable-ldap \
  --enable-spamassassin-plugin \
  --enable-gpgme \
  --enable-openssl \
  --enable-aspell \
  --target=$ARCH-slackware-linux || exit 1
make || exit 1
make install DESTDIR=$PKG \
faqdir=$DESTDIR/usr/doc/$NAME-$VERSION/faq \
manualdir=$DESTDIR/usr/doc/$NAME-$VERSION/manual || exit 1
find $PKG/ -type d -name bin -o -name sbin | xargs -r chown -R root.bin
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded 
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs strip --strip-debug
)
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  ABOUT-NLS AUTHORS ChangeLog COPYING NEWS READM* RELEASE_NOTES.claws TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/share/{man,doc} -maxdepth 0 | xargs -r -i mv {} $PKG/usr/
find $PKG/usr/info -name dir | xargs -r rm
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

mkdir $PKG/usr/share/{applications,pixmaps}
cat sylpheed-claws.desktop | sed 's/sylpheed-claws.png/\/usr\/share\/pixmaps\/sylpheed-claws.png/' > $PKG/usr/share/applications/sylpheed-claws.desktop
cat sylpheed-claws.png > $PKG/usr/share/pixmaps/sylpheed-claws.png

cd $PKG || exit 1
mv usr/bin/*-slackware-linux-sylpheed-claws usr/bin/sylpheed-claws

makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ];then
rm -rf $PKG $TMP/$NAME-$VERSION
fi


