#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://ftp.gnome.org/pub/GNOME/sources/NetworkManager/0.6/NetworkManager-0.6.5.tar.bz2
# MD5SUMS: 7d22b8df56d65d7c966cb28e0772d305 NetworkManager-0.6.4.tar.bz2
# MD5SUMS: b827d300eb28458f6588eb843cba418d NetworkManager-0.6.5.tar.bz2
# REQUIRES: dbus desktop-file-utils dhcdbd dhcp gnome-panel hal iproute2 libgcrypt libnl libnotify libxcb wpa_supplicant
# OPTIONAL: libglade libgnomeui
#
# Make sure you use the modfied dhcp found in testing/!

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.6.5
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/NetworkManager-$VERSION.tar.bz2
cd NetworkManager-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --docdir=/usr/doc/$NAME-$VERSION \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --program-prefix="" \
  --enable-shared \
  --with-distro=slackware \
  --enable-notification-icon \
  $ARCH-slackware-linux
sed -i "s,#define NETWORK_MANAGER_UTILS_H,&\n\n#define HEADERS_KERNEL 1," \
  src/NetworkManagerUtils.h
make
make install DESTDIR=$PKG
( cd $PKG/etc/rc.d
  mv rc.networkmanager rc.networkmanager.new
)
sed -i "s,local pidlist=.*,local pidlist=\`pgrep -x NetworkManager\`," \
  $PKG/etc/rc.d/rc.networkmanager.new
sed -i 's,<policy at_console="true">,<policy group="uucp">,' \
  $PKG/etc/dbus-1/system.d/*
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL NEWS README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh
( cd $PKG; find * -name "*.new" ) | xargs -rl echo config >>$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/NetworkManager-$VERSION
  rm -rf $PKG
fi
