#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://savannah.nongnu.org/download/tpb/tpb-0.6.4.tar.gz
# MD5SUMS: 563b544fbedcc1763130a0bca1ad63b6 tpb-0.6.4.tar.gz
# REQUIRES: x11
# OPTIONAL: libSM libX11 xosd

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.6.4
ARCH=${ARCH:-i486}
BUILD=4tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/tpb-$VERSION.tar.gz
cd tpb-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --program-prefix="" \
  --disable-schemas-install \
  --`which xosd-config >/dev/null 2>&1 && echo enable || echo disable`-xosd \
  $ARCH-slackware-linux
make -j
make install DESTDIR=$PKG
mv $PKG/etc/tpbrc $PKG/etc/tpbrc.new
mkdir -p $PKG/etc/udev/rules.d
cat >$PKG/etc/udev/rules.d/99-nvram.rules <<EOF
KERNEL=="nvram",        GROUP="kmem", MODE="664"
EOF
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/doc $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  ABOUT-NLS COPYING CREDITS ChangeLog README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh
( cd $PKG; find * -name "*.new" ) | xargs -rl echo config >>$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/tpb-$VERSION
  rm -rf $PKG
fi

exit $?

# This chunk has been added by autoport, part of portpkg.berlios.de:

#+configure-opts
  --`which xosd-config >/dev/null 2>&1 && echo enable || echo disable`-xosd \
#+configure-opts
#+install
mv $PKG/etc/tpbrc $PKG/etc/tpbrc.new
mkdir -p $PKG/etc/udev/rules.d
cat >$PKG/etc/udev/rules.d/99-nvram.rules <<EOF
KERNEL=="nvram",        GROUP="kmem", MODE="664"
EOF
#+install
