#!/bin/sh
# MAINTAINER: Johannes Weiner 'hnaz' <hnazfoo at googlemail dot com>
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://www1.mplayerhq.hu/MPlayer/releases/MPlayer-1.0rc2.tar.bz2
# MD5SUMS: f82bb2bc51b6cd5e5dd96f88f6f98582 MPlayer-1.0rc1.tar.bz2
# MD5SUMS: 7e27e535c2d267637df34898f1b91707 MPlayer-1.0rc2.tar.bz2
# REQUIRES: cxxlibs libtermcap
# OPTIONAL: aalib arts cdparanoia desktop-file-utils divx4linux esound
# OPTIONAL: faac fribidi glib glib2 gtk+ gtk+2 lame libXv libXxf86dga
# OPTIONAL: libcaca libdv libjpeg libmad libmpcdec libogg libpng
# OPTIONAL: libtheora libungif libvorbis lzo mesa mplayer-codecs
# OPTIONAL: mplayer-fonts mplayer-skins ncurses samba sdl slang speex
# OPTIONAL: svgalib x11 x11-devel x264 xvidcore zlib

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.0rc2
ARCH=${ARCH:-i486}
BUILD=3tom

if [ "$ARCH" = "i386" ]; then
  OPT="--enable-runtime-cpudetection"
elif [ "$ARCH" = "i486" ]; then
  OPT="--enable-runtime-cpudetection"
elif [ "$ARCH" = "s390" ]; then
  OPT="--enable-runtime-cpudetection"
elif [ "$ARCH" = "x86_64" ]; then
  OPT="--enable-runtime-cpudetection"
else
  OPT="--disable-runtime-cpudetection"
fi
# binutils >= 2.17?
BINUTILS_VER=`as --version | grep "Binutils" | egrep -o "[.0-9]+"`
case $BINUTILS_VER in
  2.1[456].*) OPT="$OPT --disable-ssse3";;
esac

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/MPlayer-$VERSION.tar.bz2
cd MPlayer-$VERSION
chown -R root.root .
CFLAGS="" \
./configure \
  --prefix=/usr \
  --confdir=/etc \
  --mandir=/usr/man \
  --enable-gui \
  --enable-dynamic-plugins \
  --enable-menu \
  $OPT
make
make install DESTDIR=$PKG
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
# Fix mencoder.1 issue (hnaz)
( cd $PKG/usr/man/man1; rm mencoder.1; ln -sf mplayer.1.gz mencoder.1.gz )
mv $PKG/usr/share/doc $PKG/usr/ || true
mv $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS Changelog LICENSE README \
  $PKG/usr/doc/$NAME-$VERSION/
# this is empty..? kill it
rmdir $PKG/etc || true
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/MPlayer-$VERSION
  rm -rf $PKG
fi

exit $?

# This chunk has been added by autoport, part of portpkg.berlios.de:

#=configure
CFLAGS="" \
./configure \
  --prefix=/usr \
  --confdir=/etc \
  --mandir=/usr/man \
  --enable-gui \
  --enable-dynamic-plugins \
  --enable-menu \
  $OPT
#=configure
#=install
make
make install DESTDIR=$PKG
#=install
#+docfiles
# this is empty..? kill it
rmdir $PKG/etc || true
#+docfiles
#+strip
# Fix mencoder.1 issue (hnaz)
( cd $PKG/usr/man/man1; rm mencoder.1; ln -sf mplayer.1.gz mencoder.1.gz )
#+strip
#=slkcflags

if [ "$ARCH" = "i386" ]; then
  OPT="--enable-runtime-cpudetection"
elif [ "$ARCH" = "i486" ]; then
  OPT="--enable-runtime-cpudetection"
elif [ "$ARCH" = "s390" ]; then
  OPT="--enable-runtime-cpudetection"
elif [ "$ARCH" = "x86_64" ]; then
  OPT="--enable-runtime-cpudetection"
else
  OPT="--disable-runtime-cpudetection"
fi
# binutils >= 2.17?
BINUTILS_VER=`as --version | grep "Binutils" | egrep -o "[.0-9]+"`
case $BINUTILS_VER in
  2.1[456].*) OPT="$OPT --disable-ssse3";;
esac
#=slkcflags
