#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: ftp://ftp.cistron.nl/pub/people/miquels/sysvinit/sysvinit-2.84.tar.gz
# MD5SUMS: 6ae4a8237a7e298097239e76eb7aff60  sysvinit-2.84.tar.gz
#
# This port was shameless cut'n'pasted from the build scripts
# written by Piter Punk found on http://piterpunk.info02.com.br/extra/.
#
# Hurray to Piter. :)
#

# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-sysvinit

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
rm -rf $PKG
mkdir -p $PKG

VERSION=2.84
ARCH=${ARCH:-i486}
BUILD=59pk

# Explode the package framework:
cd $PKG
explodepkg $CWD/_sysvinit.tar.gz

cd $TMP
rm -rf sysvinit-$VERSION
tar xzvf $CWD/sysvinit-$VERSION.tar.gz
cd sysvinit-$VERSION
chown -R root.root .
zcat $CWD/sysvinit.diff.gz | patch -p1 -E --verbose --backup --suffix=.orig
cd doc
mkdir -p $PKG/usr/doc/sysvinit-$VERSION
cp -a Install Propaganda sysvinit-$VERSION.lsm \
  $PKG/usr/doc/sysvinit-$VERSION
chmod -R 644 $PKG/usr/doc/sysvinit-$VERSION/*
chmod 755 $PKG/usr/doc/sysvinit-$VERSION
cd ../src
make clobber
make
for program in halt init killall5 shutdown runlevel ; do
  strip $program
  cat $program > $PKG/sbin/$program
done
strip last
cat last > $PKG/usr/bin/last
mv $PKG/sbin/init $PKG/sbin/init.new
# This version is old.  We use genpower now.
#cat wall > $PKG/usr/bin/wall
#strip powerd
#cat powerd > $PKG/sbin/powerd
cp initscript.sample $PKG/sbin/initscript.sample
cd ../man
cat last.1 | gzip -9c > $PKG/usr/man/man1/last.1.gz
for page in inittab.5 initscript.5 ; do
  cat $page | gzip -9c > $PKG/usr/man/man5/$page.gz
done
for page in halt.8 init.8 killall5.8 pidof.8 poweroff.8 reboot.8 runlevel.8 \
  shutdown.8 telinit.8 ; do
  cat $page | gzip -9c > $PKG/usr/man/man8/$page.gz
done
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
makepkg -l y -c n $TMP/sysvinit-$VERSION-$ARCH-$BUILD.tgz

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/sysvinit-$VERSION
  rm -rf $PKG
fi
