#!/bin/sh
# MAINTAINER: Viktor Kojouharov 'sat' <viktor@bloka.org>
# SOURCES: http://ftp.mozilla.org/pub/mozilla.org/nspr/releases/v4.6.6/src/nspr-4.6.6.tar.gz
# MD5SUMS: ba49bc35e2068f54893d3ea7031ad59c nspr-4.6.6.tar.gz

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`

VERSION=4.6.6
ARCH=${ARCH:-i486}
BUILD=1sat

PKG=$TMP/$NAME-$VERSION/build/target

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
  SLKCFG="--enable-64bit"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/nspr-$VERSION.tar.gz
cd nspr-$VERSION
chown -R root.root .
cd build
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
../mozilla/nsprpub/configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --libdir=/usr/lib/nspr \
  --program-prefix="" \
  --disable-static \
  --enable-shared \
  --enable-optimize \
  --disable-debug \
  $SLKCFG \
  $ARCH-slackware-linux
make
make install

rm dist/bin/lib*.so
rm -rf dist/include/nspr/md

mkdir -p $PKG/usr/lib/nspr
cp -Lr dist/bin $PKG/usr
cp -Lr dist/include $PKG/usr
cp -Lr dist/lib/* $PKG/usr/lib/nspr/
cp config/nspr-config $PKG/usr/bin
mkdir $PKG/usr/lib/pkgconfig
cp $CWD/nspr.pc.in $PKG/usr/lib/pkgconfig/nspr.pc
sed -e "s,@libdir@,/usr/lib/nspr,g" \
	      -e "s,@prefix@,/usr,g" \
	      -e "s,@exec_prefix@,\$\{prefix},g" \
	      -e "s,@includedir@,\$\{prefix}/include/nspr," \
	      -e "s,@NSPR_VER@,`$PKG/usr/bin/nspr-config --version`,g" \
	      -e "s,@NSS_VERSION@,$NSS_VMAJOR.$NSS_VMINOR.$NSS_VPATCH,g" \
	      -i $PKG/usr/lib/pkgconfig/nspr.pc
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/nspr-$VERSION
  rm -rf $PKG
fi
