#!/bin/sh
# MAINTAINER: Vadim Shevchenko 'shv' <shevadim@mail.ru>
# SOURCES: http://switch.dl.sourceforge.net/sourceforge/qbittorrent/qbittorrent-1.0.0.tar.gz
# MD5SUMS: e31fe47590dfa48c52d0e35d4627d630 qbittorrent-1.0.0.tar.gz
# REQUIRES: qt4 libtorrent glib2
# OPTIONAL: curl imagemagick desktop-file-utils

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.0.0
ARCH=${ARCH:-i486}
BUILD=1shv

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/qbittorrent-$VERSION.tar.gz
cd qbittorrent-$VERSION
chown -R root.root .


export QTDIR=/usr/lib/qt4
export PATH=$QTDIR/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$QTDIR/lib

./configure \
  --prefix=/usr \
#  $ARCH-slackware-linux
#   --disable-schemas-install \

make -j 2
make INSTALL_ROOT=$PKG install
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/ || true
mv $PKG/usr/share/doc $PKG/usr/ || true
mv $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING Changelog INSTALL NEWS README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/qbittorrent-$VERSION
  rm -rf $PKG
fi
