#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://ftp.gnome.org/pub/GNOME/sources/gdm/2.18/gdm-2.18.1.tar.bz2
# MD5SUMS: 7e46bc3b0a5b08e79f1f2f1b869caf40 gdm-2.14.9.tar.bz2
# MD5SUMS: a569a8275f0e0396e6ef5f63c5f56ad5 gdm-2.18.0.tar.bz2
# MD5SUMS: a80e26d98adbe485aac0f9aee64b92b1 gdm-2.18.1.tar.bz2
# REQUIRES: gnome-doc-utils libglade libgnomecanvas librsvg popt x11
# OPTIONAL: dbus-glib desktop-file-utils gksu libgnomesu scrollkeeper

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.18.1
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/gdm-$VERSION.tar.bz2
cd gdm-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc/X11 \
  --localstatedir=/var/lib \
  --program-prefix="" \
  --disable-scrollkeeper \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG

#mv $PKG/etc/X11/gdm/gdm.conf{,.new}
cp config/gdm.conf $PKG/etc/X11/gdm/gdm.conf.new
mkdir -p $PKG/usr/share/faces

mkdir -p $PKG/etc/X11/dm/Sessions 
cp -a \
    $CWD/*.desktop \
    $PKG/etc/X11/dm/Sessions
chmod 755 $PKG/etc/X11/dm/Sessions/*

mkdir -p $PKG/etc/X11/gdm
cp $CWD/Xsession $PKG/etc/X11/gdm
chmod 755 $PKG/etc/X11/gdm/Xsession

chown -R gdm.gdm $PKG/var/lib/gdm
chmod 750 $PKG/var/lib/gdm

mkdir -p $PKG/var/log/gdm
rm -rf $PKG/var/lib/log/gdm
( cd $PKG/var/lib/log/gdm 
  ln -sf ../../log/gdm .
)
(
cd $PKG/usr/share/applications
if which gnomesu; then
  sed -i '/^Exec=/s/=/=gnomesu /' gdmsetup.desktop
elif which gksu; then
  sed -i '/^Exec=/s/=/=gksu /' gdmsetup.desktop
fi
)

# make it work with rc.4:
ln -s /usr/sbin/gdm $PKG/usr/bin/gdm 
ln -s /usr/sbin/gdmsetup $PKG/usr/bin/gdmsetup 

rm -rf $PKG/var/lib/scrollkeeper
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL NEWS README README.install TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh
( cd $PKG; find * -name "*.new" ) | xargs -rl echo config >>$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gdm-$VERSION
  rm -rf $PKG
fi
