#!/bin/sh
# prepare -- sync documentation with portpkg.berlios.de wiki
#            do this before releasing a new portpkg

if ! [ -x /usr/bin/elinks ]; then
  echo
  echo "No package 'elinks' installed!"
  exit 1
fi

for doc in FrontPage QuickStart PortpkgGuide TodoBugsAbout QuestionsAndAnswers Links; do
  wget -O $doc.html http://portpkg.berlios.de/doc.php?page=$doc
  elinks -no-numbering -dump $doc.html | grep -v "^[ ]*EditThisPage" >README.$doc
  rm $doc.html
done

mv README{.TodoBugsAbout,}
mv README.FrontPage NEWS
sed -i "0,/^News$/d" NEWS
sed -i "1s,.*,News\n," NEWS
