#!/bin/sh
# prepare -- sync documentation with portpkg.berlios.de wiki
#            do this before releasing a new portpkg

if ! [ -x /usr/bin/elinks ]; then
  echo
  echo "No package 'elinks' installed!"
  exit 1
fi

for doc in FrontPage QuickStart PortpkgGuide TodoBugsAbout QuestionsAndAnswers Links; do
  wget -O $doc.html http://portpkg.berlios.de/doc.php?page=$doc
  elinks -no-numbering -dump $doc.html | grep -v "^[ ]*EditThisPage" >README.$doc
  rm $doc.html
done

sed -i "0,/^News$/d" README.FrontPage
sed -i "1s,.*,News\n," README.FrontPage
sed -i "/ file:\/\//d" README.*
mv README.TodoBugsAbout ABOUT
mv README.PortpkgGuide README
mv README.FrontPage NEWS
mv README.QuestionsAndAnswers FAQ

# this is a testing release
mv README README.orig
mv README.cp README
