#!/bin/sh
# MAINTAINER: Johannes Weiner 'hnaz' <hnazfoo at googlemail dot com>
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://dl.sourceforge.net/sourceforge/scummvm/scummvm-0.11.0.tar.bz2
# MD5SUMS: 5066301a182b7e0f1da1eec21c80024f scummvm-0.11.0.tar.bz2
# MD5SUMS: a935499011c59441fcce8322ea1c4f1d scummvm-0.7.1.tar.bz2
# MD5SUMS: 60c6977add285175c1133a3017512ce7 scummvm-0.8.2.tar.bz2
# REQUIRES: alsa-lib flac gcc-g++ libmad libvorbis sdl zlib
## REQUIRES: cxxlibs sdl x11 x11-devel
## OPTIONAL: alsa-lib flac gcc-g++ libmad libogg libvorbis nasm zlib

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.11.0
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/scummvm-$VERSION.tar.bz2
cd scummvm-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --mandir=/usr/man
make
make install DESTDIR=$PKG
mkdir -p $PKG/usr/doc
mv $PKG/usr/share/doc/scummvm $PKG/usr/doc/$NAME-$VERSION
rmdir $PKG/usr/share/doc
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/ || true
mv $PKG/usr/share/doc $PKG/usr/ || true
mv $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING COPYRIGHT NEWS README TODO doc \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/scummvm-$VERSION
  rm -rf $PKG
fi

exit $?

# This chunk has been added by autoport, part of portpkg.berlios.de:

#=config
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --mandir=/usr/man
#=config
#=install
make
make install DESTDIR=$PKG
mkdir -p $PKG/usr/doc
mv $PKG/usr/share/doc/scummvm $PKG/usr/doc/$NAME-$VERSION
rmdir $PKG/usr/share/doc
#=install
