#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# MAINTAINER: Tomas Stefano 'lem' <stefano@cedo.cz>
# SOURCES: http://search.cpan.org/CPAN/authors/id/M/MI/MIROD/XML-Twig-3.29.tar.gz
# MD5SUMS: 70be541c68247b1394138eb2e1dc109a XML-Twig-3.17.tar.gz
# MD5SUMS: fd1931464e28fb7ad082439bc2c11c2c XML-Twig-3.29.tar.gz
# REQUIRES: perl

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=3.29
ARCH=noarch
BUILD=1tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/XML-Twig-$VERSION.tar.gz
cd XML-Twig-$VERSION
cat $CWD/*.patch | patch -p1 --verbose
chown -R root.root .
perl Makefile.PL
make
make install DESTDIR=$PKG
find $PKG/ -name perllocal.pod | xargs -r rm -fv
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  MANIFEST README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/XML-Twig-$VERSION
  rm -rf $PKG
fi
