#!/bin/sh
#
# SlackBuild for yp-tools
#
##################################
## Creator: Stefano Stabellini  ##
## stefano@stabellini.net       ##
## http://www.stabellini.net    ##
##################################
#

CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
PKG=/tmp/package-yp-tools

VERSION=2.8
ARCH=${ARCH:-i486}
BUILD=1stb
	
if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG
echo "+===================+"
echo "| yp-tools-$VERSION |"
echo "+===================+"
cd $TMP
rm -rf yp-tools-$VERSION
tar xvzf $CWD/yp-tools-$VERSION.tar.gz
cd yp-tools-$VERSION
chown -R root.root .
find . -perm 777 -exec chmod 755 {} \;
find . -perm 775 -exec chmod 755 {} \;
find . -perm 700 -exec chmod 755 {} \;
find . -perm 744 -exec chmod 755 {} \;
find . -perm 666 -exec chmod 644 {} \;
find . -perm 664 -exec chmod 644 {} \;
find . -perm 600 -exec chmod 644 {} \;
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib --mandir=/usr/man
make
make install DESTDIR=$PKG
strip $PKG/usr/sbin/*
strip $PKG/usr/bin/*
chown -R root.bin $PKG/bin
chown -R root.bin $PKG/usr/bin
chown -R root.bin $PKG/usr/sbin
gzip -9 $PKG/usr/man/man1/*
gzip -9 $PKG/usr/man/man5/*
gzip -9 $PKG/usr/man/man8/*
mkdir -p $PKG/usr/doc/yp-tools-$VERSION
cp COPYING $PKG/usr/doc/yp-tools-$VERSION
cp README $PKG/usr/doc/yp-tools-$VERSION
cp INSTALL $PKG/usr/doc/yp-tools-$VERSION
cp NEWS $PKG/usr/doc/yp-tools-$VERSION
cp ABOUT-NLS $PKG/usr/doc/yp-tools-$VERSION
cp AUTHORS $PKG/usr/doc/yp-tools-$VERSION
cp TODO $PKG/usr/doc/yp-tools-$VERSION
cp THANKS $PKG/usr/doc/yp-tools-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cd $PKG
makepkg -l y -c n ../yp-tools-$VERSION-$ARCH-$BUILD.tgz

