--- Makefile.old	2003-12-08 10:28:02.000000000 +0100
+++ Makefile	2005-01-17 19:51:53.000000000 +0100
@@ -9,7 +9,7 @@
 
 ### enable ppm support ###
 DEFINES  += -D_HAVE_LIB_PPM_
-LIBS     += -lppm
+LIBS     += -lnetpbm
 
 ### enable PNG support ###
 DEFINES += -D_HAVE_PNG_
