#!/bin/sh
#
# Autoport -- An Automatic SlackBuild Generator
# Copyright (C) 2004, 2005 Thomas Pfaff <topf@users.berlios.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

source `which portpkg` || exit 1
t=`mktemp -d`

#sections="config post-config install post-install strip doc post-doc"

ask()
{
  $i_act || return
  echo
  echo -n "$@ "
  s=""
  read s
}

check()
{
  local pattern=$1
  shift
  local desc=`echo $pattern | sed "s,[\^\$],,g"`
  if egrep -qe "$pattern" "$@" 2>/dev/null; then
    row "Checking for $desc... yes"
    return 0
  else
    row "Checking for $desc... no"
    return 1
  fi
}

snip()
{
  # the #:tag ... #:tag method
  sed -i "/^#:$1$/,/^#:$1$/d" $2
  # the xxx ##tag method
  sed -i "/ *##$1$/d" $2
}

encode()
{
  local ver=`echo $version | sed "s,\.,\.,g"`
  local enc=`echo "$@" | sed -e "s,$name,\\$NAME,g" -e "s,$ver,\\$VERSION,g"`
#  local test
#  local NAME=$name
#  local VERSION=$version
#  eval test=\"$enc\"
  # try ${NAME} and ${VERSION}
  [ "`decode "$enc"`" != "$@" ] && enc=`echo "$@" | sed -e "s,$name,\\${NAME},g" -e "s,$ver,\\${VERSION},g"`
  echo "$enc"
}

decode()
{
#  local dec=`echo "$@" | sed "s,[{}],,g" -e "s,\\$NAME,$name,g" -e "s,\\$VERSION,$version,g"`
#  echo "$dec"
  local NAME=$name
  local VERSION=$version
  eval echo \"$@\"
}

add_inst() # rel/path/to/command_to_add file
{
  local s1=`basename $(echo $1 | cut -d " " -f 1)`
  local s2=`basename $2`
  # check for old style ("command bla")
  if grep -sq "$s1" $2 && ! grep -sq "^if .*/$s1" $2; then
    # one-liner: remove it
    sed -i "\,$s1,d" $2
  fi
  # remove to make sure, it's correct
  [ -f $2 ] && sed -i "/^if .*\/$s1/,/^fi$/d" $2
  # check for new style ("if [ -x command ]; then...")
  if ! grep -sq "$s1" $2; then
    row "Adding $s1 to $s2"
    echo "if [ -x `echo $1 | cut -d " " -f 1` ]; then" >>$2
    echo "  $1 >/dev/null 2>&1" >>$2
    echo "fi" >>$2
  fi
}

remove_inst() # command_to_remove file
{
  local s1=`basename $1`
  local s2=`basename $2`
  if grep -sq "$s1" $2; then
    row "Removing unneeded $s1 from $s2"
    # check for new style ("if [ -x command ]; then...")
    if grep -sq "^if .*/$s1" $2; then
      sed -i "/^if .*\/$s1/,/^fi$/d" $2
    else
      # old style ("command bla")
      sed -i "\,$s1,d" $2
    fi
  fi
}

# first: do we have tags?
[ "$MY_TAG" ] || die "No tag set. Please run 'pp-config'!"

# defaults
i_act=true
force=false
sources=""
name=""
group=""
arch=$ARCH
build=""
build_pkg=false

# parse options
shorts="afv:g:n:u:bh"
args=`getopt -qo $shorts -- "$@"`
[ "$?" == "0" ] || die "Bad Arguments! Try: autoport -h"
eval set -- "$args"
if [ "$*" ]; then
  while [ "$1" ]; do
    case $1 in
      -a)
        i_act=false;;
      -f)
        force=true;;
      -v)
        version=$2
        shift;;
      -g)
        group=`echo $2 | any2dir`
        shift;;
      -n)
        name=$2
        shift;;
      -u)
        get_info $2
        # use abstract url
        sources=`encode "$sources"`
        arch=`echo $package | rev | cut -d - -f 2 | rev`
        shift;;
      -b)
        build_pkg=true;;
      -h)
        # usage
        stanza "Usage: autoport [-a] [-n name] [-v version] [-g group] [-u port] [-b] [source url]
Options:
  -a             Run non-interactive (use defaults)
  -f             Force to re-autobuild a port when non-interactve
  -n name        Preset name of port
  -v version     Preset version of port
  -g group       Preset group of port
  -u port        Use port
  -b             Execute portpkg after port generation
  source url     Preset URL of source code (if not found via -u)"
        exit 1;;
      *://*)
        sources=$1;;
    esac
    shift
  done
fi

$i_act && stanza "Autoport -- An Automatic SlackBuild Generator
Copyright (C) 2004, 2005 Thomas Pfaff <topf at users dot berlios dot de>
Autoport comes with ABSOLUTELY NO WARRANTY. This is free software, and you
are welcome to redistribute it under certain conditions.

Autoport is quite experimental. A source code URL given, it will download and
unpack the code and searche for different keywords to adjust a suitable
SlackBuild script. If autoport doesn't work as expected, please mail at:
<topf at users dot berlios dot de>"

#[ "$sources" ] || die "No source url specified! Try: autoport --help"
[ "$group" ] || group=local

ask "* First step: Collect information. Continue? (ctrl-c to quit)"

# sources
ask "Source file URL [$sources]:"
sources=${s:-$sources}
[ "$sources" ] || die "Nothing entered. Eh? I can't help you this way!"
sources=`echo "$sources" | sed -e "s,://prdownloads\.,://dl.," -e "s,\?download$,,"`
# we can only handle _one_ source file
src=`echo "$sources" | head -n 1`
# name: guess it, if we haven't yet it
file=`basename $(decode $src)`
raw_name=`echo $file | rev | cut -d - -f 2- | rev`
[ "$name" ] || name=`echo $raw_name | tr "A-Z" "a-z"`
ask "Name [$name]:"
name=${s:-$name}
# group
ask "Group [$group]:"
group=${s:-$group}
# version
if ! [ "$version" ]; then
  # version: should be always guessed
  version=`echo $file | rev | cut -d - -f 1 | rev`
  version=`basename $version .tar.gz`
  version=`basename $version .tar.bz2`
  version=`basename $version .tgz`
fi
ask "Version [$version]:"
version=${s:-$version}
srcver=$version
version=`echo $version | sed "s,-,,g"`
# correct GNOME urls when updating an existing build script
if [ "$script" ]; then
  sver=`echo $version | cut -d . -f 1-2`
  case `decode $src` in
    *.gnome.org/pub/*/sources/$raw_name/$sver/$raw_name-$version.tar.*)
      ;; # good
    *.gnome.org/pub/*/sources/$raw_name/*/$raw_name-$version.tar.*)
      # wrong url
      wrong_sver=`echo "$src" | rev | cut -d / -f 2 | rev`
      src=`echo "$src" | sed "s,/$wrong_sver/,/$sver/,g"`
      sources=`echo "$sources" | sed "s,/$wrong_sver/,/$sver/,g"`;;
  esac
fi
# arch
ask "Arch [$arch]:"
arch=${s:-$arch}
# build: check if we need to increase it
n=1
gpkg=`ls_loc | loc2gpkg | grep -m 1 "^$group/$name-$version-$arch-[0-9]*$MY_TAG$"`
if [ $gpkg ]; then
  $i_act && stanza "There is already $gpkg."
  # find it
  while [ "$group/$name-$version-$arch-$n$MY_TAG" != $gpkg ]; do
    ((n++))
    [ "$n" == "1000" ] && die "Strange: Cannot find build number!"
  done
  # now that we found it, we can find a bigger number too!
  ((n++))
fi
ask "Build [$n$MY_TAG]:"
build=${s:-$n$MY_TAG}
# desc
if [ "$description" ]; then
  desc1=`echo "$description" | sed "s,^$name:[ ]*,," | head -n 1`
  desc2=`echo "$description" | sed "s,^$name:[ ]*,," | sed "1,2d"`
else
  desc1=$raw_name
fi
ask "Description (1-liner) [$desc1]:"
desc1=${s:-$desc1}
if $i_act; then
  stanza "Description (details) (Write or paste and finish with a single '.')"
  echo "[$desc2]"
  s=""
  while [ "$l" != "." ]; do
    read l
    s="$s
$l"
  done
  s=`echo "$s" | sed -e "1d" -e "/^\.$/d"`
fi
desc2=${s:-$desc2}
# combine $desc1 and $desc2
len=${#name}
desc=`{ echo "$name: $desc1"
        echo "$name:"
        echo "$desc2" | fmt -u -w $((75-len)) | sed "s,^,$name: ,"
        for i in 1 2 3 4 5 6 7 8 9; do
          echo "$name:"
        done; } | head -n 11`

if [ "$group" != "local" ] && [ "$script" ]; then
  path=`dirname $script`
else
  path=$PRT_DIR/$group/$name
  script=$path/SlackBuild
fi

if $i_act; then
  echo
  echo "Creating now a port with this information:"
  echo
  echo "PACKAGE NAME:  $name-$version-$arch-$build"
  echo "SCRIPT LOCATION:  $script"
  echo "SOURCE LOCATION:  $sources" | fmt -u
  echo "PACKAGE DESCRIPTION:"
  echo "$desc"
fi

ask "Last chance to quit. Port scripts will now be written.
* Next step: Downloading and checking source code. Continue? (ctrl-c to quit)"

# now we should redecode the actual source name
sources=`decode "$sources"`
src=`echo "$sources" | head -n 1`
file=`basename $(decode $src)`

if [ -f $path/stop.autoport ]; then
  stanza "There's a warning not to autoport this source code:"
  echo "==========================================="
  more $path/stop.autoport
  echo "==========================================="
  die
fi
if [ -d $path ]; then
  ask "* This port ($path) already exists. Really go on? (ctrl-c to quit)"
  # quit if not -f in non-interactive mode
  if ! $i_act && ! $force && \
  [ "`grep "^VERSION=" $script | cut -d = -f 2-`" = "$version" ]; then
    error "There's already a build script for that version. Skipping.
(Use -f to force a re-autoport!)"
    exit 0
  fi
  cp $script $script.new
  script=$script.new
fi

stanza "Autoporting $group/$name-$version-$arch-$build:"
mkdir -p $path
touch $script

# check for fixes in the script (style: #+post-config-fix)
#for i in $sections; do
grep -o "^#+.*-fix$" $script | cut -c 3- | sort -u | while read s; do
  row "Extracting inlined $s"
  sed -n "/^#+$s$/,/^#+$s$/p" $script >$path/$s.autoport
  sed -i "/^#+$s$/,/^#+$s$/d" $script
#  # ...and old-style (post-config-fix.autoport) files
#  if [ -f $path/$i-fix.autoport ]; then
#    echo "#+$i-fix" >$t/$i-fix
#    cat $path/$i-fix.autoport >>$t/$i-fix
#    echo "#+$i-fix" >>$t/$i-fix
#    # obsolete
#    rm $path/$i-fix.autoport
#  fi
#  [ -s $t/$i-fix ] && row "Found $i-fix" || rm $t/$i-fix
done
# (...and style #[+-=]section)
grep -o "^#+.*$" $script | cut -c 3- | sort -u | while read s; do
  row "Extracting inlined (new-style) post-$s"
  sed -n "/^#+$s$/,/^#+$s$/p" $script >$path/post-$s-fix.autoport
  sed -i "/^#+$s$/,/^#+$s$/d" $script
done
grep -o "^#=.*$" $script | cut -c 3- | sort -u | while read s; do
  row "Extracting inlined (new-style) $s"
  sed -n "/^#=$s$/,/^#=$s$/p" $script >$path/$s-fix.autoport
  sed -i "/^#=$s$/,/^#=$s$/d" $script
done
grep -o "^#-.*$" $script | cut -c 3- | sort -u | while read s; do
  row "Extracting inlined (new-style) $s"
  >$path/$s-fix.autoport
  sed -i "/^#-$s$/d" $script
done
# remove #[+-=] lines form .autoport files
sed -i "/^#[+-=]/d" $path/*.autoport 2>/dev/null

# downlaod source file
#file=`basename $src`
if [ -f $SRC_DIR/$file ]; then
  row "$file found in $SRC_DIR/"
else
  row "Downloading $file"
  VERBOSE=true
  output=/dev/stdout
  get `decode $src` $SRC_DIR/$file || die
fi

# write skeletons
failed=false
sed '/^#:SlackBuild.skel$/,/^#:SlackBuild.skel$/!d' $0 >$script
echo `encode "$sources"` >$path/sources
echo "$desc" >$path/slack-desc
sed -i "s,%version%,$version," $script
sed -i "s,%build%,$build," $script

# format
echo -n "  --> Checking format... "
mkdir -p $t/src
case $file in
  *.tar.bz2)
    format=tarbz2
    tar xjf $SRC_DIR/$file -C $t/src/ || die "Error while unpacking, maybe wrong URL?"
    tar tjf $SRC_DIR/$file >$t/footprint
    echo ".tar.bz2"
    sed -i "s,%tarmode%,j," $script
    snip rpm $script;;
  *tar.gz|*.tgz) # yes, there was one file called "xxxtar.gz"!
    format=targz
    tar xzf $SRC_DIR/$file -C $t/src/ || die "Error while unpacking, maybe wrong URL?"
    tar tzf $SRC_DIR/$file >$t/footprint
    echo ".tar.gz"
    sed -i "s,%tarmode%,z," $script
    snip rpm $script;;
  *.src.rpm)
    format=srpm
    ( cd $t/
      rm -rf `basename $file .rpm`.tar.gz
      cp $SRC_DIR/$file .
      rpm2targz $file
      tar xzf `basename $file .rpm`.tar.gz
      tar xzf `basename $file .src.rpm`/$name-$version.tar.gz -C $t/src/
      tar tzf `basename $file .src.rpm`/$name-$version.tar.gz >$t/footprint ) \
    || die "Error while unpacking, maybe wrong URL?"
    echo ".src.rpm"
    snip tar $script;;
  *)
    echo "unknown!"
    die "Unknown source format, please write SlackBuild by hand!";;
esac
tarball=`encode "$file"`
sed -i "s,%tarball%,$tarball," $script

# source-prefix
echo -n "  --> Checking source-prefix... "
srcdir_prefix=`cat $t/footprint | sed "s,^\./,,;s,/.*,," | sort -u`
if [ `echo "$srcdir_prefix" | wc -l` == 1 ] && [ "$srcdir_prefix" != "." ]; then
  echo "$srcdir_prefix/"
  if [ "$format" == "srpm" ]; then
#    snip cd_sdp $script
    :
  else
    snip extra_sdp $script
  fi
  srcdir_prefix_out=`encode "$srcdir_prefix"`
  sed -i "s,%srcdirprefix%,$srcdir_prefix_out," $script
else
  echo "no prefix"
  snip cd_sdp $script
  srcdir_prefix="."
  mkdir $t/src/$name-$version
  mv $t/src/* $t/src/$name-$version
  rm -rf $TMP/$name-$version
fi

# now, move it to $TMP as user expects it to be
[ "`whoami`" = "root" ] && chown nobody.nogroup -R $t/src/*
rm -rf $TMP/$srcdir_prefix
mv $t/src/* $TMP/

# snip srcdir_prefixed in footprint
sed -i "s,^\./,," $t/footprint
sed -i "s,^$srcdir_prefix/,," $t/footprint

# insert fixes
#for i in $sections; do
for i in `ls $path/*-fix.autoport 2>/dev/null`; do
  i=`basename $i -fix.autoport`
#  if [ -f $t/$i-fix ]; then
  if egrep -sq "^#%(|post-)$i-fix%$" $script; then
    row "Fixing $i"
    # if it's not a post-xxx, then it's meant to replace the section
    case $i in
      post-*)
        sed -i "\,^#%$i-fix%$,r$path/$i-fix.autoport" $script;;
      *)
        sed -i "\,^#%post-$i-fix%$,r$path/$i-fix.autoport" $script
        snip $i $script;;
    esac
  else
    die "Couldn't locate $i fix. Maybe you're using the wrong version of autoport?"
  fi
done

# include patches
if [ "`ls $path/*.patch 2>/dev/null`" ]; then
  row "Including patches (Please check them later!)"
else
  snip patch $script
fi

# docs
if grep -sq "#:doc" $script; then
  docs=`egrep "^ABOUT$|^ABOUT-NLS$|^ANNOUNCE$|^AUTHORS$|^CONFIGURATION$|^CHANGES$\
  |^COPYING$|^COPYRIGHT$|^CREDITS$|^ChangeLog$|^Changelog$|^CHANGELOG$\
  |^CONTRIBUTORS$|FAQ|^FEATURES$|^FILES$|^HACKING$|^History$|^HISTORY$|^INSTALL\
  |^LICENSE$|^LSM$|^MANIFEST$|^NEWS$|README|Readme|^SITES$|RELEASE|^RELNOTES$\
  |^THANKS$|^TIPS$|^TODO$|^VERSION$|^CONFIGURATION|^GPL$|^License$|^Doc$|^doc$\
  |^Docs|^docs|^Roadmap$|^ROADMAP$|BUGS|^index.ht|INDEX" $t/footprint \
  | grep -v / | sort -u | xargs`
  if [ "$docs" ]; then
    row "Checking docs... $docs."
    sed -i "s,%docs%,$docs," $script
  else
    row "Checking docs... none."
    snip docs $script
  fi
fi

# configure/make
if grep -sqe "#:config" -e "#:make" $script; then
  if check "^Makefile.PL$" $t/footprint; then
    # Makefile.PL is first choice
    snip cfg_autogen $script
    snip configure $script
    arch=noarch
  else
    snip perl $script
    if check "^configure$" $t/footprint; then
      if check "KDEDIRS" $TMP/$srcdir_prefix/configure; then
        sed -i "s,%prefix%,opt/kde,g" $script
        snip ac_sysconfdir $script
        snip ac_localstatedir $script
      else
        check "--prefix" $TMP/$srcdir_prefix/configure || snip ac_prefix $script
        check "--sysconfdir" $TMP/$srcdir_prefix/configure || snip ac_sysconfdir $script
        check "--localstatedir" $TMP/$srcdir_prefix/configure || snip ac_localstatedir $script
      fi
      check "--program-prefix" $TMP/$srcdir_prefix/configure || snip ac_program_prefix $script
      check "--disable-static" $TMP/$srcdir_prefix/configure || snip ac_disable_static $script
      check "--disable-scrollkeeper" $TMP/$srcdir_prefix/configure || snip ac_disable_scrollkeeper $script
      check "--disable-update-mimedb" $TMP/$srcdir_prefix/configure || snip ac_disable_update_mimedb $script
      snip cfg_autogen $script
    elif check "^autogen.sh$" $t/footprint; then
      :
    else
      snip configure $script
      snip cfg_autogen $script
      if check "^setup\.py$" $t/footprint; then
#        snip cfg_mk_hard $script
        snip mk $script
        arch=noarch
      else
        error "Don't know how to build this package."
        failed=true
      fi
    fi
  fi
fi

# set the prefix to /usr if this is still undefined
sed -i "s,%prefix%,usr,g" $script

# installation prefix
if grep -sq "#:install" $script; then
  if check "^Makefile" $t/footprint; then
    snip python $script
    # Makefile.PL will always use DESTDIR
    if grep -sq "^Makefile.PL$" $t/footprint \
    || check "DESTDIR" $TMP/$srcdir_prefix/Makefile*; then
      snip inst_PREFIX $script
      snip inst_prefix $script
#      snip inst $script
#      snip cfg_mk_hard $script
    else
      snip inst_destdir $script
      if check "PREFIX" $TMP/$srcdir_prefix/Makefile*; then
        snip inst_prefix $script
#        snip inst $script
#        snip cfg_mk_hard $script
      else
        snip inst_PREFIX $script
        if check "prefix" $TMP/$srcdir_prefix/Makefile*; then
#          snip inst $script
#          snip cfg_mk_hard $script
          :
        else
          snip inst_prefix $script
          if check "/usr/local" $TMP/$srcdir_prefix/{,*/}Makefile*; then
            :
          else
            error "Don't know how to install this package (no install-prefix)."
            failed=true
          fi
        fi
      fi
    fi
  # as always, check setup.py at last! use configure if possible!
  elif check "^setup\.py$" $t/footprint; then
#    snip cfg_mk_hard $script
    snip inst_destdir $script
    snip inst_PREFIX $script
    snip inst_prefix $script
  else
    error "Don't know how to install this package (no Makefile)."
    failed=true
  fi
fi

# cflags
if ! check "CFLAGS" $TMP/$srcdir_prefix/*; then
  snip cflags $script
fi

# cxxflags
use_cxxflags=true
if ! check "CXXFLAGS" $TMP/$srcdir_prefix/*; then
  snip cxxflags $script
fi

# slkcflags
grep -sqe "CFLAGS" -e "CXXFLAGS" $script || snip slkcflags $script

# gconf schemas
if check "\.schemas(|\.in|\.in\.in)$" $t/footprint; then
  if ! grep -sq "^gconf()" $path/doinst.sh; then
    row "Adding gconf() to doinst.sh"
    sed '/^#:doinst.sh_gconf$/,/^#:doinst.sh_gconf$/!d' $0 >>$path/doinst.sh
  fi
else
  if grep -sq "^gconf()" $path/doinst.sh; then
    row "Removing unneeded gconf() from doinst.sh"
    sed -i "/^gconf()/,/^}$/d" $path/doinst.sh
  fi
  snip schemas $script
fi

# icon-cache
if check "^index.theme(|\.in|\.in\.in)$" $t/footprint; then
  if ! grep -sq "usr/bin/gtk-update-icon-cache " $path/doinst.sh; then
    row "Adding gtk-update-icon-cache to doinst.sh"
    sed '/^#:doinst.sh_icons$/,/^#:doinst.sh_icons$/!d' $0 >>$path/doinst.sh
  fi
else
  snip icons $script
fi

# old inst()
if grep -sq "^inst()" $path/doinst.sh; then
  row "Removing old inst() from doinst.sh"
  sed -i "/^inst()/,/^}$/d" $path/doinst.sh
fi

# scrollkeeper
if check "\.omf(|\.in)$" $t/footprint; then
  add_inst "usr/bin/scrollkeeper-update -p var/lib/scrollkeeper" $path/doinst.sh
else
  remove_inst "scrollkeeper-update" $path/doinst.sh
  snip scrollkeeper $script
fi

# mime-update
if check "\.(keys|mime)(|\.in|\.in\.in)$" $t/footprint; then
  add_inst "usr/bin/update-mime-database usr/share/mime" $path/doinst.sh
else
  remove_inst "update-mime-database" $path/doinst.sh
  snip mime-database $script
fi

# desktop-database
if check "\.desktop(|\.in|\.in\.in)$" $t/footprint; then
  add_inst "usr/bin/update-desktop-database" $path/doinst.sh
else
  #remove_inst "update-desktop-database" $path/doinst.sh
  grep -sq "update-desktop-database" $path/doinst.sh \
  && warn "update-desktop-database seems removed. Please check!"
fi

## wrong hard-coded doc paths
#if ! check "/share/doc" $TMP/$srcdir_prefix/{,*/}Makefile*; then
#  snip fix_mk_doc $script
#fi

## wrong hard-coded man paths (force on Makefile.PL)
#if ! grep -sq "^Makefile.PL$" $t/footprint \
#&& ! check "/share/man" $TMP/$srcdir_prefix/{,*/}Makefile*; then
#  snip fix_mk_man $script
#fi

# config() subroutine?
if grep -sq "\.new" $script; then
  if ! grep -sq "^config()" $path/doinst.sh; then
    row "Adding config() to doinst.sh"
    sed '/^#:doinst.sh_config$/,/^#:doinst.sh_config$/!d' $0 >>$path/doinst.sh
  fi
else
  if grep -sq "^config()" $path/doinst.sh; then
    row "Removing unneeded config() from doinst.sh"
    sed -i "/^config()/,/^}$/d" $path/doinst.sh
  fi
fi

# if doinst.sh is emtpy, remove it
if [ -f $path/doinst.sh ] && ! [ -s $path/doinst.sh ]; then
  row "Removing empty doinst.sh"
  rm $path/doinst.sh
fi

# doinst.sh at all?
[ -f $path/doinst.sh ] || snip doinst $script

# now arch should be known
case $arch in
  noarch)
    sed -i "s,%arch%,$arch," $script
    snip cflags $script
    snip strip $script;;
  *)
    # we know better than the user ;-)
    sed -i "s,%arch%,\${ARCH:-i486}," $script;;
esac

# clean up
sed -i "/^#[:#%]/d" $script
sed -i "s, *##[^ ]*,,g" $script
if [ -f $path/doinst.sh ]; then
  sed -i "/^#/d" $path/doinst.sh
  sed -i "s, *##[^ ]*,,g" $path/doinst.sh
fi

# summary
if [ -f $path/readme.autoport ]; then
  stanza "There's a readme for this port:"
  echo "==========================================="
  more $path/readme.autoport
  echo "==========================================="
fi

# any errors?
$failed && die "There's been an error. Please write SlackBuild by hand."

# rename the new script
case $script in *.new)
  script=`echo $script | sed "s,\.new$,,"`
  mv $script.new $script
esac

# portpkg?
if $build_pkg; then
  ask "* Next step: Call portpkg. Continue? (ctrl-c to quit)"
  # ok, if this port is new, it has no dependencies, if it's rewritten,
  # let's assume, the user wants to rebuild only this port
  cd $PRT_DIR/$group/$name
  portpkg -b #-q $group/$name
fi

exit 0

#----------------------------------------

#:SlackBuild.skel
#:head
TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

#:head
#%post-head-fix%
#:vars
VERSION=%version%
##SRCVER=%srcver% ##srcver
ARCH=%arch%
BUILD=%build%

#:vars
#%post-vars-fix%
#:slkcflags
if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

#:slkcflags
#%post-slkcflags-fix%
#:prepare
rm -rf $PKG
mkdir -p $PKG/%prefix%
cd $TMP
rm -rf $NAME-$VERSION ##extra_sdp
mkdir -p $NAME-$VERSION ##extra_sdp
cd $NAME-$VERSION ##extra_sdp
##rm -rf %srcdirprefix% ##cd_sdp
rpm2targz $CWD/%tarball% ##rpm
tar xzvf `basename %tarball% .rpm`.tar.gz ##rpm
tar xzvf $NAME-$VERSION.tar.gz ##rpm
tar x%tarmode%vf $CWD/%tarball% ##tar
cd %srcdirprefix% ##cd_sdp
cat $CWD/*.patch | patch -p1 --verbose ##patch
chown -R root.root .
##find . -perm %perm644% -exec chmod 644 {} \; ##perms644
##find . -perm %perm755% -exec chmod 755 {} \; ##perms755
#:prepare
#%post-prepare-fix%
#:config
#:configure
./autogen.sh ##cfg_autogen
CFLAGS="$SLKCFLAGS" \ ##cflags
CXXFLAGS="$SLKCFLAGS" \ ##cxxflags
./configure \
#:configure-opts
  --prefix=/%prefix% \ ##ac_prefix
  --sysconfdir=/etc \ ##ac_sysconfdir
  --localstatedir=/var/lib \ ##ac_localstatedir
  --program-prefix="" \ ##ac_program_prefix
  --disable-static \ ##ac_disable_static
  --disable-scrollkeeper \ ##ac_disable_scrollkeeper
  --disable-update-mimedb \ ##ac_disable_update_mimedb
#:configure-opts
#%post-configure-opts-fix%
  $ARCH-slackware-linux
#:configure
#%post-configure-fix%
perl Makefile.PL ##perl
##find -name Makefile | xargs sed -i "s,/usr/local/etc,$PKG/etc,g" ##cfg_mk_hard
##find -name Makefile | xargs sed -i "s,/usr/local/var,$PKG/var,g" ##cfg_mk_hard
##find -name Makefile | xargs sed -i "s,/usr/local,$PKG/usr,g" ##cfg_mk_hard
##find -name Makefile | xargs sed -i "s,/share/doc,/doc,g" ##fix_mk_doc
##find -name Makefile | xargs sed -i "s,/share/man,/man,g" ##fix_mk_man
#:config
#%post-config-fix%
#:install
make ##mk
##make PREFIX=/usr ##mk_PREFIX
##make prefix=/usr ##mk_prefix
GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 \ ##schemas
make install DESTDIR=$PKG ##inst_destdir
make install PREFIX=$PKG/%prefix% ##inst_PREFIX
make install prefix=$PKG/%prefix% ##inst_prefix
##make install ##inst
python setup.py build install --root=$PKG ##python
#:install
#%post-install-fix%
#:refine
##mkdir -p $PKG/etc/gconf/gconf.xml.defaults ##schemas
##GCONF_CONFIG_SOURCE="xml::$PKG/etc/gconf/gconf.xml.defaults" \ ##schemas
##gconftool-2 --makefile-install-rule $PKG/etc/gconf/schemas/*.schemas ##schemas
##find $PKG/etc/gconf/ -name "%gconf.xml" | xargs -r rm ##schemas
rm -rf $PKG/usr/lib/perl?/?.?.?/*-linux/perllocal.pod ##perl
rm -rf $PKG/var/lib/scrollkeeper ##scrollkeeper
rm -rf $PKG/%prefix%/info/dir
find $PKG -name mimeinfo.cache -exec rm -fv {} \; ##mime-database
find $PKG/ -type d -name bin -o -name sbin | xargs -r chown -R root.bin
#:refine
#%post-refine-fix%
#:strip
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
#:strip
#%post-strip-fix%
#:doc
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
#:docfiles
cp -a \ ##docs
#:docfiles2
  %docs% \ ##docs
#:docfiles2
#%post-docfiles2-fix%
  $PKG/usr/doc/$NAME-$VERSION/ ##docs
#:docfiles
#%post-docfiles-fix%
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
#:doc
#%post-doc-fix%
#:tail
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh ##doinst
find $PKG/etc/gconf/schemas/ -name "*.schemas" | sed "s,^$PKG/,gconf ," >>$PKG/install/doinst.sh ##schemas
( cd $PKG; find -name index.theme ) | xargs -l echo icons >>$PKG/install/doinst.sh ##icons

#:tail
#%post-tail-fix%
#:package
cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

#:package
#%post-package-fix%
#:cleanup
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/%srcdirprefix%
  rm -rf $PKG
fi
#:cleanup
#%post-cleanup-fix%
#:SlackBuild.skel

#:doinst.sh_config
config() {
  NEW="$1"
  OLD="`dirname $NEW`/`basename $NEW .new`"
  # If there's no config file by that name, mv it over:
  if [ ! -r $OLD ]; then
    mv $NEW $OLD
  elif [ "`cat $OLD | md5sum`" = "`cat $NEW | md5sum`" ]; then # toss the redundant copy
    rm $NEW
  fi
  # Otherwise, we leave the .new copy for the admin to consider...
}
#:doinst.sh_config
#:doinst.sh_gconf
gconf() {
  if [ -x usr/bin/gconftool-2 ]; then
    GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule $1 >/dev/null 2>&1
  fi
}
#:doinst.sh_gconf
#:doinst.sh_icons
icons() {
  if [ -x usr/bin/gtk-update-icon-cache ]; then
    usr/bin/gtk-update-icon-cache `dirname $1` >/dev/null 2>&1
  fi
}
#:doinst.sh_icons
