#!/bin/bash
# Update CVS main ChangeLog (DEVELOPERS ONLY)
# Needs CVS access.
#
# DO THIS FROM A CLEAN CVS TREE, NOT FROM YOUR WORKING PORTS TREE

. `which portpkg` || exit 1

mailhost=users.berlios.de

cd $PRT_DIR || die

has_prog rcs2log || die

pause "Continue update main ChangeLogs in $PRT_DIR? (ctrl-c to abort)"

rm ChangeLog

# use mail host for emails
rcs2log -i 2 -h $mailhost >ChangeLog

# "Updated." lines are unnecessary
sed -i "/: Updated.$/{N;d}" ChangeLog
cvs ci -m "Updated." ChangeLog
