.TH PORTPKG 1 "November 21, 2004" "Slackware Linux" "User Manuals"
.SH NAME
portpkg \- build a package by source and install it
.SH SYNOPSIS
portpkg [action] [options] [list ..]
.PP
while list can be one of these forms:
.IP
group/
.IP
[group/]portname[-version-arch-build]
.SH DESCRIPTION
portpkg starts a so called port script (SlackBuild) found in
/usr/ports/<portgroup>/<portname>/ and installs the resulting package to
your system.
.SH ACTIONS
There can be only one alternative action. If none specified, the default
action is to check for required ports, then download the source, then
build a binary package and install it.
.IP "-d, --diff"
List the difference between installed and available port versions.
.IP "-f, --find"
Find ports by search patterns.
.IP "-h, --help"
Show help page.
.IP "-i, --info"
Show information about ports.
.IP "-l, --list"
List all (or specified) available ports.
.IP "-s, --sync"
Synchronise your ports tree in /usr/ports with the official tree.
.IP "-u, --upgrade"
Upgrade all (!) outdated ports shown by --diff (so-called "dist-upgrade").
.IP "-v, --version"
Show version information about portpkg.
.SH OPTIONS
There can be multiple options at once.
.IP "-o, --download"
Download source files only.
.IP "-b, --rebuild"
Rebuild the package if already build.
.IP "-e, --reinstall"
Reinstall the package, if already installed.
.IP "-g, --verbose"
Show SlackBuild output instead of piping it to /tmp/buildlog-<portname>.
.IP "-q, --noreqs"
Disable checking for required ports.
.IP "-y, --dryrun"
Disable downloading, building and installing. Just show what would happen.
.SH EXAMPLES
.IP "portpkg foobar"
.IP "portpkg --diff"
.IP "portpkg --find moz"
.IP "portpkg --info mozilla galeon"
.IP "portpkg --list"
.IP "portpkg --list l/ foo n/arg"
.IP "portpkg --list foobar-1.0-i486-1"
.IP "portpkg --sync"
.IP "portpkg --upgrade"
.SH DIRECTORIES
.IP /usr/ports
The ports archive portpkg needs to build packages.
.IP /usr/src/dist
The source files portpkg downloaded for ports.
.IP /usr/obj/pkg
The packages portpkg made of ports.
.SH FILES
.IP /usr/ports/local.conf
The configuration file for optional settings, mostly written by
interactive scripts.
.PP
Several configuration files are distributed and can be expanded by \.local files:
.IP "/usr/ports/mirrors and mirrors.local"
List of mirrors to be used when downloading files. 
.IP "/usr/ports/ignore and ignore.local"
List of ports to ignore when making the "requires" file.
.IP "/usr/ports/exclude and exclude.local"
List of ports to exclude when doing upgrades or diffs.
.SH AUTHOR
Thomas Pfaff <topf at users dot berlios de>
.SH "SEE ALSO"
.BR installpkg(8)
.BR removepkg(8)
.BR upgradepkg(8)  	
