.TH PORTPKG 1 "OCTOBER 2004" Linux "User Manuals"
.SH NAME
portpkg \- make a package by a script and install it
.SH SYNOPSIS
.B portpkg [
.I action
.B ] [
.I options
.B ] [
.I list
.B ... ]
.IP while
.I list
can be one of these forms:
.IP
.I group/
.IP
.B [
.I group/
.B ]
.I portname
.B [
.I -version-arch-build
.B ]
.SH DESCRIPTION
portpkg starts a so called port script (SlackBuild) found in
/usr/ports/*/<portname>/ and installs the resulting package to your system.
.SH ACTIONS
There can be only one alternative action. If none specified, the default
action is to build and install.
.IP "-d, --diff"
List the difference between installed and available port versions.
.IP "-f, --find"
Find ports by search patterns.
.IP "-h, --help"
Show help page.
.IP "-i, --info"
Show information about ports.
.IP "-l, --list"
List all (or specified) available ports.
.IP "-s, --sync"
Synchronise your ports tree in /usr/ports with the official tree.
.IP "-u, --upgrade"
Upgrade all (!) outdated ports shown by --diff.
.IP "-v, --version"
Show version information about portpkg.
.SH OPTIONS
There can be multiple options at once.
.IP "-o, --download"
Download source files only.
.IP "-b, --rebuild"
Rebuild the package if already build.
.IP "-e, --reinstall"
Reinstall the package, if already installed.
.IP "-g, --showcompile"
Show SlackBuild output instead of piping it to /tmp/buildlog-<portname>.
.SH EXAMPLES
.IP "portpkg foobar"
.IP "portpkg --diff"
.IP "portpkg --find moz"
.IP "portpkg --info mozilla galeon"
.IP "portpkg --list"
.IP "portpkg --list l/ foo n/arg"
.IP "portpkg --list foobar-1.0-i486-1"
.IP "portpkg --sync"
.IP "portpkg --upgrade"
.SH DIRECTORIES
.I /usr/ports
.RS
The ports archive portpkg needs to build packages.
.RE
.I /usr/src/dist
.RS
The source files portpkg downloaded for ports.
.RE
.I /usr/obj/pkg
.RS
The packages portpkg made of ports.
.RE
.SH FILES
.I /usr/ports/maintain
.RS
The configuration file for maintainer information.
.RE
.I /usr/ports/mirrors
.RS
List  of mirrors to be used when downloading files. 
.RE
.I /usr/ports/ignore
.RS
List of ports to ignore when making the "requires" file.
.RE
.I /usr/ports/exclude
.RS
List of ports to exclude when doing upgrades or diffs.
.RE
.SH AUTHOR
Thomas Pfaff <toastbrot at web de>
.SH "SEE ALSO"
.BR installpkg(8)
.BR removepkg(8)
.BR upgradepkg(8)  	
