#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# REQUIRES: bin coreutils findutils grep gzip pkgtools sed shadow tar util-linux
# OPTIONAL: cvs fakeroot gcc glibc gnupg lynx svn wget

VERSION=0.38
ARCH=noarch
BUILD=4tom

TMP=${TMP:-bla}

CWD=`pwd`
NAME=`basename $CWD`
PKG=/tmp/package-$NAME
rm -rf $PKG

# directories
mkdir -p $PKG/etc/portpkg/plugins
mkdir -p $PKG/usr/bin
mkdir -p $PKG/usr/man/man1

# configuration
install -m 644 $CWD/repos $PKG/etc/portpkg/repos.new
install -m 644 $CWD/mirrors $PKG/etc/portpkg/mirrors.new
install -m 644 $CWD/ignore $PKG/etc/portpkg/ignore.new
install -m 644 $CWD/exclude $PKG/etc/portpkg/exclude.new
install -m 644 $CWD/use $PKG/etc/portpkg/use.new
install -m 644 $CWD/sync.* $PKG/etc/portpkg/plugins/
install -m 644 $CWD/export.* $PKG/etc/portpkg/plugins/
install -m 644 $CWD/virtual $PKG/etc/portpkg/virtual.new

# man page
install -m 644 $CWD/portpkg.1 $PKG/usr/man/man1/

# executables
install -m 755 $CWD/portpkg $PKG/usr/bin/
sed -i -r "s,^(ENGINE_VER=).*$,\1$VERSION," $PKG/usr/bin/portpkg
install -m 755 $CWD/pp-config $PKG/usr/bin/
install -m 755 $CWD/checkpkg $PKG/usr/bin/
install -m 755 $CWD/autoport $PKG/usr/bin/

#chown -R root.bin $PKG/usr/bin
gzip -9 $PKG/usr/man/man?/*
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  ABOUT COPYING CREDITS FAQ INSTALL NEWS README* ROADMAP \
  $PKG/usr/doc/$NAME-$VERSION/
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n /tmp/$NAME-$VERSION-$ARCH-$BUILD.tgz
