#!/bin/sh
# sync-slack - portpkg-addon for using slackware source as ports

#include "portpkg.h"
source `which portpkg` || exit 1

RSYNC=rsync://rsync.slackware.at/slackware/slackware-current/source
DIST=ftp://ftp.slackware.com/pub/slackware/slackware-current
TREE=/usr/src/pseudo/slack

is_root || die
mkdir -p $TREE
cd $TREE || die
has_pkg rsync-2.6
# sync source/ and remove files we don't need
rsync -avz --delete \
--exclude "FILE_LIST" \
--exclude "MANIFEST.*" \
--exclude "CHECKSUMS*" \
--exclude "README.TXT" \
--exclude "*.tar.gz" \
--exclude "*.tar.bz2" \
--exclude "*.tgz" \
--exclude "*.tar.Z" \
--exclude "*.bin" \
--exclude "*.zip" \
$RSYNC/* .

# write missing files into sources-files
stanza "Building sources-files..."
t=`private`
row "Retrieving file list"
get $DIST/FILELIST.TXT $t.file_list
row "Constructing ports"
# for any file
grep -o "\./source/.*/.*/.*" $t.file_list \
| cut -d " " -f 1 | cut -d / -f 3- | while read s; do
    # if not found, add it to "sources"
    if ! find $s >/dev/null 2>&1; then
#	echo `echo $s | cut -d / -f 3-`
#    else
	echo $DIST/source/$s
    fi | grep -ve "SlackBuild$" -e "^slack-desc$" -e "^doinst.sh" \
    >>`echo $s | cut -d / -f 1-2`/sources
done

row "Checking if wrappers needed" 
find -name "*.build" | while read s; do
    dir=`dirname $s`
    gname=`dirname $s | cut -c 3-`
    group=`echo $gname | cut -d / -f 1`
    name=`echo $gname | cut -d / -f 2`
    ver=`grep ^VERSION= $s | cut -d = -f 2-`
    arch=`grep ^ARCH= $s | cut -d = -f 2- | sed -re "s,\\\\$\\{[A-Z]*:-,," -e "s,},,"`
    build=1slack
    cat <<EOF >$dir/SlackBuild
VERSION=$ver
ARCH=$arch
BUILD=$build

checkinstall -S -y \\
  --pkgname=$name \\
  --pkgarch=$arch \\
  --pkgrelease=$build \\
  --pakdir=/tmp \\
  --strip=yes \\
  --stripso=yes \\
  --gzman=yes \\
  --backup=no \\
  "sh `basename $s`" || exit 1
EOF
done

stanza "Don't forget, to link $TREE in $PRT_DIR, to use it!"
