#!/bin/sh
# sync-slack - portpkg-addon for using slackware source as ports

#include "portpkg.h"
source `which portpkg` || exit 1

RSYNC=rsync://rsync.slackware.at/slackware/slackware-current/source
DIST=ftp://ftp.slackware.at/slackware-current
TREE=~/pseudo/slack

mkdir -p $TREE
cd $TREE || die

has_pkg rsync-2.6
# sync source/ and remove files we don't need
rsync -avz --delete \
--exclude "FILE_LIST" \
--exclude "MANIFEST.*" \
--exclude "CHECKSUMS*" \
--exclude "README.TXT" \
--exclude "*.tar.gz" \
--exclude "*.tar.bz2" \
--exclude "*.tgz" \
--exclude "*.tar.Z" \
--exclude "*.bin" \
--exclude "*.zip" \
$RSYNC/* .

# write missing files into sources-files
stanza "Building sources-files..."
t=`private`
row "Retrieving file list..."
get $DIST/FILELIST.TXT $t.file_list
row "Constructing ports..."
grep -o "\./source/.*/.*/.*" $t.file_list \
| cut -d " " -f 1 | cut -d / -f 3- | while read s; do
    if find $s >/dev/null 2>&1; then
	echo `echo $s | cut -d / -f 3-`
    else
	echo $DIST/$s
    fi | grep -ve "SlackBuild$" -e "^slack-desc$" -e "^doinst.sh$" \
    >>`echo $s | cut -d / -f 1-2`/sources
done

stanza "Don't forget, to link $TREE in $PRT_DIR, to use them!"

# todo: *.build-wrapper?
