#!/bin/sh
#
# SlackBuild for sarg
#
##################################
## Creator: Stefano Stabellini  ##
## stefano@stabellini.net       ##
## http://www.stabellini.net    ##
##################################
#

CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
PKG=/tmp/package-sarg

VERSION=2.0.5
ARCH=${ARCH:-i486}
BUILD=1stb

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG
mkdir -p $PKG/usr/bin
mkdir -p $PKG/etc/sarg
mkdir -p $PKG/usr/man/man1
mkdir -p $PKG/var/www/htdocs
echo "+===============+"
echo "| sarg-$VERSION |"
echo "+===============+"
cd $TMP
rm -rf sarg-$VERSION
tar xvzf $CWD/sarg-$VERSION.tar.gz
cd sarg-$VERSION
chown -R root.root .
find . -perm 777 -exec chmod 755 {} \;
find . -perm 775 -exec chmod 755 {} \;
find . -perm 700 -exec chmod 755 {} \;
find . -perm 744 -exec chmod 755 {} \;
find . -perm 666 -exec chmod 644 {} \;
find . -perm 664 -exec chmod 644 {} \;
find . -perm 600 -exec chmod 644 {} \;
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure --enable-bindir=$PKG/usr/bin --enable-sysconfdir=/etc/sarg --enable-htmldir=$PKG/var/www/htdocs --enable-mandir=$PKG/usr/man/man1
make
make install DESTDIR=$PKG
strip $PKG/usr/bin/*
strip $PKG/usr/sbin/*
chown -R root.bin $PKG/usr/bin
chown -R root.bin $PKG/usr/sbin
gzip -9 $PKG/usr/man/man1/*
mkdir -p $PKG/usr/doc/sarg-$VERSION
cp BETA-TESTERS $PKG/usr/doc/sarg-$VERSION 
cp COPYING $PKG/usr/doc/sarg-$VERSION
cp LICENSE $PKG/usr/doc/sarg-$VERSION
cp CONTRIBUTORS $PKG/usr/doc/sarg-$VERSION
cp DONATIONS $PKG/usr/doc/sarg-$VERSION
cp ChangeLog $PKG/usr/doc/sarg-$VERSION
cp README $PKG/usr/doc/sarg-$VERSION
cp README $PKG/usr/doc/sarg-$VERSION
mkdir -p $PKG/install
mkdir -p $PKG/etc/sarg
cp -R /etc/sarg/* $PKG/etc/sarg
rm $PKG/etc/sarg/sarg.conf
cp $CWD/sarg.conf.new $PKG/etc/sarg
cp $CWD/exclude_hosts.new $PKG/etc/sarg
mv $PKG/etc/sarg/exclude_codes $PKG/etc/sarg/exclude_codes.new
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh
cd $PKG
makepkg -l y -c n ../sarg-$VERSION-$ARCH-$BUILD.tgz

