( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf Sylpholution )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/Sylpholution Sylpholution )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf Korillaws )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/Korillaws Korillaws )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf GurUnix )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/GurUnix GurUnix )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf OldDark )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/OldDark OldDark )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf orbit-claws )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/orbit-claws orbit-claws )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf black )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/black black )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf blue_anarchy )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/blue_anarchy blue_anarchy )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf achileus-noname )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/achileus-noname achileus-noname )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf SylZilla )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/SylZilla SylZilla )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf Graphitte-0.9.7 )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/Graphitte-0.9.7 Graphitte-0.9.7 )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf XeNtish )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/XeNtish XeNtish )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf Gnomeria )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/Gnomeria Gnomeria )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf mongrel2 )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/mongrel2 mongrel2 )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf mozilla )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/mozilla mozilla )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf gnomaws )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/gnomaws gnomaws )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf tom_2.1.1 )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/tom_2.1.1 tom_2.1.1 )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf New_Session )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/New_Session New_Session )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf Gorillaws )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/Gorillaws Gorillaws )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf Everaldo_Kids )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/Everaldo_Kids Everaldo_Kids )
( cd usr/doc/sylpheed-claws-themes-1.0 ; rm -rf Logos-1.0.1 )
( cd usr/doc/sylpheed-claws-themes-1.0 ; ln -sf /usr/share/sylpheed/themes/Logos-1.0.1 Logos-1.0.1 )
