#!/bin/sh
# MAINTAINER: Tomas Stefano 'lem' <stefano at cedo dot cz>
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://ftp.gnome.org/pub/GNOME/sources/gwget/0.99/gwget-0.99.tar.bz2
# MD5SUMS: 79a3625ef99a5a417164e0d97020fcc5 gwget-0.93.tar.gz
# MD5SUMS: 69f43ae6edbb7ac472c30c547fbf80e6 gwget-0.99.tar.bz2
# REQUIRES: desktop-file-utils gconf libglade libgnomeui
# OPTIONAL: libnotify

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.99
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/gwget-$VERSION.tar.bz2
cd gwget-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --docdir=/usr/doc/$NAME-$VERSION \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --program-prefix="" \
  --enable-shared \
  --disable-schemas-install \
  $ARCH-slackware-linux
make
GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 \
make install DESTDIR=$PKG
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL NEWS README THANKS TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh
( cd $PKG; find etc/gconf/schemas/ -name "*.schemas" ) | xargs -rl echo gconf >>$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gwget-$VERSION
  rm -rf $PKG
fi
