#!/bin/sh
# MAINTAINER: Piotr Simon 'sjn' <sajmon@tenboard.com>
# MAINTAINER: Piotr Simon 'sjn' <sajmon@users.berlios.de>
# SOURCES: http://heanet.dl.sourceforge.net/sourceforge/libetpan/libetpan-0.54.tar.gz
# MD5SUMS: 0135cf6a9d97afb1f75001f514448836 libetpan-0.45.tar.gz
# MD5SUMS: afa4abd73665e1a46b0510c4f4efa9a9 libetpan-0.46.tar.gz
# MD5SUMS: f6c973ea1aa53d947f034e093960da10 libetpan-0.49.tar.gz
# MD5SUMS: 119eb4ac27fb75540ca74d8997f7fc7f libetpan-0.52.tar.gz
# MD5SUMS: 0214de45b1b92277fbfc6c9a00af5316 libetpan-0.54.tar.gz
# REQUIRES: cyrus-sasl db42 openssl
# OPTIONAL: curl db44 expat gcc-g++
set -e
TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.54
ARCH=${ARCH:-i686}
BUILD=1sjn

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mtune=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
rm -rf $NAME-$VERSION
tar xzvf $CWD/$NAME-$VERSION.tar.gz
cd $NAME-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  --disable-static \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
rm -rf $PKG/usr/info/dir

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  ChangeLog COPYRIGHT NEWS \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/$NAME-$VERSION
  rm -rf $PKG
fi
