#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://lpn.rnbhq.org/download/vobcopy-1.0.1.tar.bz2
# MD5SUMS: 5a5efee3b678da69b391eb76b15fc49f vobcopy-1.0.0.tar.bz2
# MD5SUMS: 0fae0c80dbe3a9dd3d06aba54275cf8d vobcopy-1.0.1.tar.bz2
# REQUIRES: libdvdread

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.0.1
ARCH=${ARCH:-i486}
BUILD=1tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/vobcopy-$VERSION.tar.bz2
cd vobcopy-$VERSION
chown -R root.root .
./configure.sh
make
make install PREFIX=$PKG/usr
find $PKG/ -name perllocal.pod | xargs -r rm -fv
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  COPYING Changelog README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/vobcopy-$VERSION
  rm -rf $PKG
fi
