#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://ftp.gnome.org/pub/gnome/sources/control-center/2.18/control-center-2.18.0.tar.bz2
# MD5SUMS: adf6804249cff2e4d2ed1b3e87035c3d control-center-2.11.6.tar.bz2
# MD5SUMS: a429f605878160e2660725bad2ee1e17 control-center-2.11.91.tar.bz2
# MD5SUMS: 06a213f801bff26cee4f5db03a54da08 control-center-2.12.0.tar.bz2
# MD5SUMS: eba22b935cfad8660a8ee1a4a0b1e47d control-center-2.13.92.tar.bz2
# MD5SUMS: 90195a0b42b94d80b0959c32162a10e3 control-center-2.14.0.tar.bz2
# MD5SUMS: 20535dc3918d896c1a1087eff003ee27 control-center-2.16.0.tar.bz2
# MD5SUMS: e5251c30c45577b78770beb2df59df5d control-center-2.18.0.tar.bz2
# REQUIRES: desktop-file-utils gconf gnome-desktop gnome-menus gst-plugins-base hal libglade libxklavier metacity nautilus scrollkeeper x11
# OPTIONAL: evolution-data-server gnome-panel gst-plugins libXScrnSaver libXft libXxf86misc libgnomekbd librsvg libxcb mozilla shared-mime-info

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.18.0
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/control-center-$VERSION.tar.bz2
cd control-center-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  --enable-shared \
  --disable-scrollkeeper \
  --disable-update-mimedb \
  $ARCH-slackware-linux
make
GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 \
make install DESTDIR=$PKG
rm -rf $PKG/var/lib/scrollkeeper
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL NEWS README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh
( cd $PKG; find etc/gconf/schemas/ -name "*.schemas" ) | xargs -rl echo gconf >>$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/control-center-$VERSION
  rm -rf $PKG
fi
