#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://www.exit1.org/dvdrip/dist/pre/Video-DVDRip-0.97.11.tar.gz
# MD5SUMS: cba0735a4170a095d833784989eae730 Video-DVDRip-0.97.11.tar.gz
# REQUIRES: event-execflow gtk2-ex-formfactory gtk2-perl libintl-perl perl transcode
# OPTIONAL: cdrdao cdrecord lsdvd mjpegtools mplayer ogmtools vcdimager video-dvdrip xine-ui

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.97.11
ARCH=noarch
BUILD=2tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/Video-DVDRip-$VERSION.tar.gz
cd Video-DVDRip-$VERSION
chown -R root.root .
perl Makefile.PL
make
make install DESTDIR=$PKG
mkdir -p $PKG/usr/share/applications
install -m 644 $CWD/dvdrip.desktop $PKG/usr/share/applications/
sed -i "s,^Icon=.*$,Icon=/`cd $PKG; find * -name icon.xpm`," $PKG/usr/share/applications/dvdrip.desktop
rm -rf $PKG/usr/lib/perl?/?.?.?/*-linux/perllocal.pod
rm -rf $PKG/usr/info/dir
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  COPYRIGHT MANIFEST README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/Video-DVDRip-$VERSION
  rm -rf $PKG
fi
