#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://ftp.gnome.org/pub/GNOME/sources/gnome-doc-utils/0.10/gnome-doc-utils-0.10.3.tar.bz2
# MD5SUMS: d59875bb5924fd098a19a7d229af63cc gnome-doc-utils-0.1.3.tar.bz2
# MD5SUMS: 43f3a4086ec1254cbe20b85948192d18 gnome-doc-utils-0.10.3.tar.bz2
# MD5SUMS: d29a3e10ff8cba17dbb6d3aff2f30bb8 gnome-doc-utils-0.3.2.tar.bz2
# MD5SUMS: 0fdb9ba6a68e0a86297f4a839087f8a7 gnome-doc-utils-0.4.1.tar.bz2
# MD5SUMS: 1e0c26e3e1159f60551aab5187634744 gnome-doc-utils-0.6.0.tar.bz2
# MD5SUMS: 3f3903e5a3e3b05261498d907f2471a9 gnome-doc-utils-0.7.2.tar.bz2
# REQUIRES: libxml2 python scrollkeeper

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.10.3
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/gnome-doc-utils-$VERSION.tar.bz2
cd gnome-doc-utils-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  --disable-scrollkeeper \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
rm -rf $PKG/var/lib/scrollkeeper
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL NEWS README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gnome-doc-utils-$VERSION
  rm -rf $PKG
fi
