#!/bin/sh
#############################
## Build script for: Squid
## Original Creator: jmedina@tuxjm.net <http://www.tuxjm.net>
##
## Modified by: Stefano Stabellini
## stafano@stabellini.net
##

# Set initial variables
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-squid

NAME=squid
#VERSION=2.5.STABLE7
VERSION=2.5.STABLE9
ARCH=x86_64
BUILD=1stb

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
rm -rf $PKG
mkdir -p $PKG

cd $TMP
rm -rf ${NAME}-${VERSION}
tar xvzf ${CWD}/${NAME}-${VERSION}.tar.gz

cd ${NAME}-${VERSION}
chown -R root.root .
find . -perm 444 -exec chmod 644 {} \;
find . -perm 777 -exec chmod 755 {} \;
for patch in $CWD/patches/squid* ; do
  zcat $patch | patch -p1 --verbose
done
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --bindir=/usr/sbin \
  --libexecdir=/usr/lib/squid \
  --datadir=/usr/share \
  --sysconfdir=/etc/squid \
  --localstatedir=/var \
  --with-pthreads \
  --enable-storeio="aufs,ufs,diskd,coss,null" \
  --enable-removal-policies="lru,heap" \
  --enable-delay-pools \
  --enable-useragent-log \
  --enable-referer-log \
  --enable-snmp \
  --enable-wccp \
  --enable-arp-acl \
  --enable-ssl \
  --enable-linux-netfilter \
  --enable-basic-auth-helpers="NCSA,YP,multi-domain-NTLM,MSNT,SMB,getpwnam,winbind" 
make
make install DESTDIR=$PKG

gzip -9 $PKG/usr/man/man?/*.?
mkdir -p $PKG/usr/doc/${NAME}-${VERSION}
cp -a doc/debug-sections.txt CREDITS RELEASENOTES.html ChangeLog CONTRIBUTORS \
  COPYING COPYRIGHT INSTALL QUICKSTART README SPONSORS \
  $PKG/usr/doc/${NAME}-${VERSION}

mkdir -p $PKG/etc/rc.d
mkdir -p $PKG/etc/logrotate.d
install -m 644 $CWD/squid.logrotate $PKG/etc/logrotate.d/squid
install -m 755 $CWD/squid.init $PKG/etc/rc.d/rc.squid
mkdir -p $PKG/var/spool/squid
chmod 750 $PKG/var/spool/squid
chmod 750 $PKG/var/log/squid

# Make symlink for the default errors directory
(cd $PKG/etc/squid
ln -snf /usr/share/squid/errors/English errors
)

( cd $PKG
find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

chown -R root.bin ${PKG}/usr/sbin
chmod -R 755 ${PKG}/usr/sbin

mkdir -p $PKG/install 
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

# Build the package:
cd $PKG
makepkg -l y -c n ${TMP}/${NAME}-${VERSION}-${ARCH}-${BUILD}.tgz

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf ${TMP}/${NAME}-${VERSION}
  rm -rf $PKG
fi
