#!/bin/sh
# MAINTAINER: Viktor Kojouharov 'sat' <viktor@bloka.org>
# SOURCES: http://ibiblio.org/pub/linux/system/emulators/wine/wine-0.9.49.tar.bz2
# MD5SUMS: d8f361e6fe7520cda983a78673cd3bda wine-0.9.37.tar.bz2
# MD5SUMS: 6d8cf3a9eef08e9dfbc3105ccd1ce648 wine-0.9.38.tar.bz2
# MD5SUMS: 6535691a7558c53bbe66455c6df559a1 wine-0.9.39.tar.bz2
# MD5SUMS: 412b64916b32c31cacd7655ffa4489b6 wine-0.9.40.tar.bz2
# MD5SUMS: 014e3760c07ac71906ba47c27f0471ab wine-0.9.41.tar.bz2
# MD5SUMS: 04e53f201e5747b86751fc0abb0c0aeb wine-0.9.42.tar.bz2
# MD5SUMS: 7b9133e717ef6ca1ab220512670d9786 wine-0.9.43.tar.bz2
# MD5SUMS: cdfc5cc1d813a955c8e7310346fb5629 wine-0.9.44.tar.bz2
# MD5SUMS: feecc3ccb4639b672d8446154a4fb700 wine-0.9.45.tar.bz2
# MD5SUMS: aa729097ddb324185a3e092b37a5f9fe wine-0.9.46.tar.bz2
# MD5SUMS: dfeeb7c137a1abab917f82dafbef5c8a wine-0.9.47.tar.bz2
# MD5SUMS: e2cc11fe7ec7769bcf8fe4f59b1dd75a wine-0.9.48.tar.bz2
# MD5SUMS: 417912f28e48ddc6c4285a493d070564 wine-0.9.49.tar.bz2
# REQUIRES: desktop-file-utils
# OPTIONAL: esound gphoto-suite lcms libSM libXxf86vm libxslt mesa openldap openldap-client perl

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.9.49
ARCH=${ARCH:-i486}
BUILD=1sat

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/wine-$VERSION.tar.bz2
cd wine-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  ANNOUNCE AUTHORS ChangeLog LICENSE README VERSION \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/wine-$VERSION
  rm -rf $PKG
fi
