#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://poppler.freedesktop.org/poppler-data-0.1.tar.gz
# MD5SUMS: 5c700eb06dda9dafec09cd85225e34d4 poppler-data-0.1.tar.gz

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.1
ARCH=${ARCH:-i486}
BUILD=1tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/poppler-data-$VERSION.tar.gz
cd poppler-data-$VERSION
chown -R root.root .
make
make install DESTDIR=$PKG prefix=/usr
find $PKG/ -name perllocal.pod | xargs -r rm -fv
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/ || true
mv $PKG/usr/share/doc $PKG/usr/ || true
mv $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  COPYING README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/poppler-data-$VERSION
  rm -rf $PKG
fi
