#!/bin/sh
# Heavily based on the Slackware 10.2 SlackBuild
# http://www.clamav.net/

CWD=`pwd`
if ["$TMP" = ""]; then
 TMP=/tmp
fi
PKG=$TMP/package-clamav
NAME=clamav
VERSION=0.87
ARCH=${ARCH:-i486}
BUILD=1stb

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mcpu=i686"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

if [ ! -d $TMP ]; then
 mkdir -p $TMP
fi
if [ ! -d $PKG ]; then
 mkdir -p $PKG
fi

cd $TMP
tar xzvf $CWD/$NAME-$VERSION.tar.gz
cd $NAME-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
./configure --prefix=/usr \
--sysconfdir=/etc/clamav \
--with-dbdir=/var/lib/clamav \
--disable-static \
--disable-clamav \
--enable-milter \
--program-prefix="" \
--program-suffix="" \
$ARCH-slackware-linux
make
make install DESTDIR=$PKG

mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS BUGS ChangeLog COPYING FAQ INSTALL NEWS README contrib docs/html docs/*.pdf \
  $PKG/usr/doc/$NAME-$VERSION

( cd $PKG/usr/man
  find . -name "*.?" | xargs gzip -9
)

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

chown -R root.bin $PKG/usr/bin
chown -R root.bin $PKG/usr/sbin
mv $PKG/etc/clamav/clamd.conf $PKG/etc/clamav/clamd.conf.new
mv $PKG/etc/clamav/freshclam.conf $PKG/etc/clamav/freshclam.conf.new
mkdir -p $PKG/etc/rc.d
zcat $CWD/rc.clamd.gz > $PKG/etc/rc.d/rc.clamd
mkdir -p $PKG/var/spool/cron/crontabs
zcat $CWD/cron.gz >> $PKG/var/spool/cron/crontabs/clamav
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh
cd $PKG
makepkg -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/$NAME-$VERSION
  rm -rf $PKG
fi
