#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://mesh.dl.sourceforge.net/sourceforge/wxwindows/wxGTK-2.8.7.tar.bz2
# MD5SUMS: 1371dd278e8f5a7e1fb821c1e3b3795b wxGTK-2.6.0.tar.bz2
# MD5SUMS: 3cd76c3c47913e52a3175dd47239c6ec wxGTK-2.6.3.tar.bz2
# MD5SUMS: b25e85eeee524903214ebb520753f4bd wxGTK-2.8.7.tar.bz2
# REQUIRES: esound gcc-g++ glib2 gtk+2 libpng libtiff x11
# OPTIONAL: libSM libXxf86vm

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.8.7
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/wxGTK-$VERSION.tar.bz2
cd wxGTK-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --program-prefix="" \
  --enable-shared \
  --disable-schemas-install \
  --enable-unicode \
  --`pkg-config libgnomeprint-2.2 && echo with || echo without`-gnomeprint \
  --`pkg-config gnome-vfs-2.0 && echo with || echo without`-gnomevfs \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
pushd contrib/src
make
make install DESTDIR=$PKG
popd
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/doc $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  docs/*.txt \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/wxGTK-$VERSION
  rm -rf $PKG
fi

exit $?

# This chunk has been added by autoport, part of portpkg.berlios.de:

#=docfiles
cp -a \
  docs/*.txt \
  $PKG/usr/doc/$NAME-$VERSION/
#=docfiles
#+configure-opts
  --enable-unicode \
  --`pkg-config libgnomeprint-2.2 && echo with || echo without`-gnomeprint \
  --`pkg-config gnome-vfs-2.0 && echo with || echo without`-gnomevfs \
#+configure-opts
#+install
pushd contrib/src
make
make install DESTDIR=$PKG
popd
#+install
