#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: ftp://ftp.isc.org/isc/dhcp/dhcp-3.0.5.tar.gz
# MD5SUMS: 004ef935fd54b8046b16bdde31a9e151 dhcp-3.0.4.tar.gz
# MD5SUMS: ce5d30d4645e4eab1f54561b487d1ec7 dhcp-3.0.5.tar.gz

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=3.0.5
ARCH=${ARCH:-i486}
BUILD=1tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/dhcp-$VERSION.tar.gz
cd dhcp-$VERSION
cat $CWD/*.patch | patch -p1 --verbose
chown -R root.root .
./configure --copts -DEXTENDED_NEW_OPTION_INFO
make LIBDIR=/usr/lib INCDIR=/usr/include
make install DESTDIR=$PKG LIBDIR=/usr/lib INCDIR=/usr/include
find $PKG/ -name perllocal.pod | xargs -r rm -fv
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  LICENSE README RELNOTES \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/dhcp-$VERSION
  rm -rf $PKG
fi
