#!/bin/sh
# MAINTAINER: Piotr Simon 'sjn' <sajmon@tenboard.com>
# SOURCES: http://home.in.tum.de/~baueran/mailfilter/mailfilter-0.8.tar.gz
# MD5SUMS: 0c03ef7f9ff214b034eaaf68515610aa mailfilter-0.6.2.tar.gz
# MD5SUMS: a935c224bfb9c10257a45206305aa832 mailfilter-0.8.tar.gz
# REQUIRES: cxxlibs
# OPTIONAL: gcc-g++ openssl
VERSION=0.8
ARCH=${ARCH:-i486}
BUILD=1sjn

CWD=`pwd`
NAME=`basename $CWD`
PKG=/tmp/package-$NAME
rm -rf $PKG
mkdir -p $PKG/usr

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

cd /tmp || exit 1
tar zxvf ${CWD}/${NAME}-${VERSION}.tar.gz
cd ${NAME}-${VERSION} || exit 1
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure --prefix=/usr $ARCH-slackware-linux || exit 1
make || exit 1 
make DESTDIR=$PKG install || exit 1

mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL \
  NEWS README THANKS TODO doc/FAQ \
  $PKG/usr/doc/$NAME-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cd $PKG
find . -type f | xargs file | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded

find . -type f -path '*/man/*man?/*.*' -path '*.[1-9]' -exec gzip -9f {} \;

makepkg -l y -c n /tmp/${NAME}-${VERSION}-${ARCH}-${BUILD}.tgz
