#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://initd.org/pub/software/pysqlite/releases/2.3/2.3.1/pysqlite-2.3.1.tar.gz
# MD5SUMS: 0ca35ad1baa94f38fb08b9793f75cdd0 pysqlite-2.3.1.tar.gz
# REQUIRES: python sqlite

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.3.1
ARCH=noarch
BUILD=1tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/pysqlite-$VERSION.tar.gz
cd pysqlite-$VERSION
chown -R root.root .
python setup.py build install --root=$PKG
mkdir -p $PKG/usr/doc
mv $PKG/usr/pysqlite2-doc $PKG/usr/doc/pysqlite-$VERSION
rm -rf $PKG/usr/lib/perl?/?.?.?/*-linux/perllocal.pod
rm -rf $PKG/usr/info/dir
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  LICENSE \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/pysqlite-$VERSION
  rm -rf $PKG
fi
