
#default skin
if [ ! -e /usr/share/mplayer/Skin/default ];then
ln -sf /usr/share/mplayer/Skin/Blue /usr/share/mplayer/Skin/default
fi

( cd usr/doc/mplayer-skins-1.0 ; rm -rf KDE )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/KDE KDE )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf QPlayer )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/QPlayer QPlayer )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf Blue )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/Blue Blue )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf mentalic )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/mentalic mentalic )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf WMP6 )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/WMP6 WMP6 )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf mini )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/mini mini )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf slim )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/slim slim )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf Canary )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/Canary Canary )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf softgrip )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/softgrip softgrip )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf xmmplayer )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/xmmplayer xmmplayer )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf Dushku )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/Dushku Dushku )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf Abyss )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/Abyss Abyss )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf Cyrus )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/Cyrus Cyrus )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf XFce4 )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/XFce4 XFce4 )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf OpenDoh )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/OpenDoh OpenDoh )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf gnome )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/gnome gnome )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf JiMPlayer )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/JiMPlayer JiMPlayer )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf phony )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/phony phony )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf trium )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/trium trium )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf webby )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/webby webby )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf xanim )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/xanim xanim )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf moonphase )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/moonphase moonphase )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf AlienMind )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/AlienMind AlienMind )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf Orange )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/Orange Orange )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf Corelian )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/Corelian Corelian )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf CornerMP )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/CornerMP CornerMP )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf xine-lcd )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/xine-lcd xine-lcd )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf sessene )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/sessene sessene )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf changuito )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/changuito changuito )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf krystal )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/krystal krystal )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf MidnightLove )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/MidnightLove MidnightLove )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf smoothwebby )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/smoothwebby smoothwebby )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf PowerPlayer )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/PowerPlayer PowerPlayer )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf handheld )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/handheld handheld )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf hayraphon )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/hayraphon hayraphon )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf BlueHeart )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/BlueHeart BlueHeart )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf QuickSilver )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/QuickSilver QuickSilver )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf iTunes )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/iTunes iTunes )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf new-age )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/new-age new-age )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf neutron )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/neutron neutron )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf netscape4 )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/netscape4 netscape4 )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf mplayer_red )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/mplayer_red mplayer_red )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf CornerMP-aqua )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/CornerMP-aqua CornerMP-aqua )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf OSX-Brushed )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/OSX-Brushed OSX-Brushed )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf Industrial )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/Industrial Industrial )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf proton )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/proton proton )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf iTunes-mini )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/iTunes-mini iTunes-mini )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf tvisor )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/tvisor tvisor )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf standard )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/standard standard )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf CubicPlayer )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/CubicPlayer CubicPlayer )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf Blue-small )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/Blue-small Blue-small )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf OSX-Mod )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/OSX-Mod OSX-Mod )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf hwswskin )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/hwswskin hwswskin )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf ultrafina )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/ultrafina ultrafina )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf avifile )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/avifile avifile )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf divxplayer )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/divxplayer divxplayer )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf bluecurve )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/bluecurve bluecurve )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf Terminator3 )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/Terminator3 Terminator3 )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf plastic )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/plastic plastic )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf plastik )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/plastik plastik )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf DVDPlayer )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/DVDPlayer DVDPlayer )
( cd usr/doc/mplayer-skins-1.0 ; rm -rf disappearer )
( cd usr/doc/mplayer-skins-1.0 ; ln -sf /usr/share/mplayer/Skin/disappearer disappearer )

