#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://balsa.gnome.org/balsa-2.3.22.tar.bz2
# MD5SUMS: 64763beb79731649da7e327b1140843a balsa-2.3.20.tar.bz2
# MD5SUMS: 0f9b8dbdd26a1916dcc92f0767e8b4e4 balsa-2.3.22.tar.bz2
# REQUIRES: desktop-file-utils gtkhtml scrollkeeper
# OPTIONAL: aspell compface gmime gpgme gtksourceview gtkspell
# OPTIONAL: libesmtp libnotify openssl pcre sqlite
# UP2DATE: http://balsa.gnome.org/download

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.3.22
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/balsa-$VERSION.tar.bz2
cd balsa-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --docdir=/usr/doc/$NAME-$VERSION \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --program-prefix="" \
  --disable-schemas-install \
  --`pkg-config gtkspell-2.0 && echo with || echo without`-gtkspell \
  --`pkg-config gtksourceview-1.0 && echo with || echo without`-gtksourceview \
  `pkg-config libssl && echo --with-ssl` \
  `pkg-config sqlite3 && echo --with-sqlite` \
  `test -x /usr/bin/gpgme-config && echo --with-gpgme=/usr/bin/gpgme-config` \
  `test -x /usr/bin/compface && echo --with-compface` \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
rm -rf $PKG/var/lib/scrollkeeper
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog HACKING INSTALL NEWS README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/balsa-$VERSION
  rm -rf $PKG
fi

exit $?

# This chunk has been added by autoport, part of portpkg.berlios.de:

#+configure-opts
  --`pkg-config gtkspell-2.0 && echo with || echo without`-gtkspell \
  --`pkg-config gtksourceview-1.0 && echo with || echo without`-gtksourceview \
  `pkg-config libssl && echo --with-ssl` \
  `pkg-config sqlite3 && echo --with-sqlite` \
  `test -x /usr/bin/gpgme-config && echo --with-gpgme=/usr/bin/gpgme-config` \
  `test -x /usr/bin/compface && echo --with-compface` \
#+configure-opts
