#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://dl.sourceforge.net/font-tool/xf86-corefonts-0.2.1.tar.gz
# MD5SUMS: 69cebd1b813b56a5e3a97cc6f0307f44  xf86-corefonts-0.2.1.tar.gz
# REQUIRES: cabextract

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.2.1
ARCH=noarch
BUILD=2tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/xf86-corefonts-$VERSION.tar.gz
cd xf86-corefonts-$VERSION
chown -R root.root .
for i in *.exe; do
  cabextract -L $i
done
mkdir -p $PKG/usr/share/fonts
install -m 644 *.ttf $PKG/usr/share/fonts/
rm -rf $PKG/usr/lib/perl?/?.?.?/*-linux/perllocal.pod
rm -rf $PKG/usr/info/dir
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  COPYING README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/xf86-corefonts-$VERSION
  rm -rf $PKG
fi
