#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://ftp.debian.org/debian/pool/main/g/gnome-ppp/gnome-ppp_0.3.23.orig.tar.gz
# MD5SUMS: 0b0c40f5252db68617cba8e5f2c9cb2e gnome-ppp-0.3.21.tar.gz
# MD5SUMS: 073c62973f95bd250f35521f26a8974d gnome-ppp-0.3.23.tar.gz
# MD5SUMS: 3f0dd26f82188d76ad93364296611588 gnome-ppp_0.3.23.orig.tar.gz
# REQUIRES: desktop-file-utils libglade wvdial

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.3.23
ARCH=${ARCH:-i486}
BUILD=2tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/gnome-ppp_$VERSION.orig.tar.gz
cd gnome-ppp-$VERSION
tar xjvf gnome-ppp-$VERSION.tar.bz2
cd gnome-ppp-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --program-prefix="" \
  --disable-static \
  --enable-shared \
  --disable-schemas-install \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/doc $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL NEWS README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gnome-ppp-$VERSION
  rm -rf $PKG
fi

exit $?

# This chunk has been added by autoport, part of portpkg.berlios.de:

#=prepare
rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/gnome-ppp_$VERSION.orig.tar.gz
cd gnome-ppp-$VERSION
tar xjvf gnome-ppp-$VERSION.tar.bz2
cd gnome-ppp-$VERSION
chown -R root.root .
#=prepare
