#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://ftp.gnome.org/pub/gnome/sources/metacity/2.20/metacity-2.20.1.tar.bz2
# MD5SUMS: 08c38e04c8ea83b524e36b17ffaec661 metacity-2.11.1.tar.bz2
# MD5SUMS: fa01d95221a64a1f6d4e088ca9b6362e metacity-2.12.0.tar.bz2
# MD5SUMS: 2480951fb0636d3fc6a78ab8a54f355d metacity-2.14.0.tar.bz2
# MD5SUMS: 5172849a35be21bda78041623eb45656 metacity-2.14.1.tar.bz2
# MD5SUMS: db1f2582681bf5eb0a8ecab45b622d7b metacity-2.16.0.tar.bz2
# MD5SUMS: 7ac14eb4caffbb15df91b70b0def2f5e metacity-2.16.5.tar.bz2
# MD5SUMS: 2af31af033618329d093267ac00e49ff metacity-2.18.0.tar.bz2
# MD5SUMS: e9c6317c85db019ac2d832dd9f45f536 metacity-2.20.0.tar.bz2
# MD5SUMS: bd4396d1a3b096c544cf0139a847fd16 metacity-2.20.1.tar.bz2
# REQUIRES: desktop-file-utils gconf gtk+2 popt
# REQUIRES: startup-notification
# OPTIONAL: libcm

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.20.1
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/metacity-$VERSION.tar.bz2
cd metacity-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --docdir=/usr/doc/$NAME-$VERSION \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --program-prefix="" \
  --enable-shared \
  --disable-schemas-install \
  --`pkg-config cm && echo enable || echo disable`-compositor \
  $ARCH-slackware-linux
make
GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 \
make install DESTDIR=$PKG
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog HACKING INSTALL NEWS README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh
( cd $PKG; find etc/gconf/schemas/ -name "*.schemas" ) | xargs -rl echo gconf >>$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/metacity-$VERSION
  rm -rf $PKG
fi

exit $?

# This chunk has been added by autoport, part of portpkg.berlios.de:

#+configure-opts
  --`pkg-config cm && echo enable || echo disable`-compositor \
#+configure-opts
