#!/bin/sh
# MAINTAINER: Vadim Shevchenko 'shv' <shevadim@mail.ru>
# SOURCES: http://download.netbeans.org/netbeans/6.0/final/zip/netbeans-6.0.1-200801291616-ml-javaee.zip
# MD5SUMS: 7cef372affe8510f2d71769daa6ebd91 netbeans-6.0.1-200801291616-ml-javaee.zip
# REQUIRES: jdk x11
# OPTIONAL: desktop-file-utils
## SOURCES: http://download.netbeans.org/netbeans/6.0/final/zip/netbeans-6.0.1-200801291616-ml.zip

TMP=/tmp
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=6.0.1
ARCH=noarch
BUILD=1shv

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
unzip $CWD/netbeans-6.0.1-200801291616-ml-javaee.zip


rm -rf `find $NAME -name *.exe` \
       `find $NAME -name *.bat` \
       `find $NAME -name *.dll` 

install -d $PKG/usr/{bin,share/$NAME,share/applications}
chown -R root.root $NAME
mv $NAME $PKG/usr/share
install -m 755 $CWD/$NAME.sh $PKG/usr/bin/$NAME
install -m 744 $CWD/NetBeans.desktop $PKG/usr/share/applications/NetBeans.desktop
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/$NAME
  rm -rf $PKG
fi
