#!/bin/sh
# MAINTAINER: Vadim Shevchenko 'shv' <shevadim@mail.ru>
# SOURCES: http://dlc.sun.com/netbeans/download/5_5/mlfcs/200612070100/netbeans-5_5.tar.bz2
# MD5SUMS: cc0564eb2c2385dbf99631f027287ed6 netbeans-5_5.tar.bz2
# REQUIRES: jdk x11
# OPTIONAL: desktop-file-utils

TMP=/tmp
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=5.5
ARCH=noarch
BUILD=1shv

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar -xjvf $CWD/netbeans-5_5.tar.bz2


rm -rf `find $NAME -name *.exe` \
       `find $NAME -name *.bat` \
       `find $NAME -name *.dll` 

install -d $PKG/usr/{bin,share/$NAME,share/applications}
chown -R root.root $NAME
mv $NAME $PKG/usr/share
install -m 755 $CWD/$NAME.sh $PKG/usr/bin/$NAME
install -m 744 $CWD/NetBeans.desktop $PKG/usr/share/applications/NetBeans.desktop
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/$NAME
  rm -rf $PKG
fi
