#!/bin/sh
# SOURCES: http://www.cosc.canterbury.ac.nz/~greg/python/Pyrex/Pyrex-0.9.4.1.tar.gz
# MD5SUMS: 425f0543c634bc7a86fe4fce02e0e882 Pyrex-0.9.4.1.tar.gz
# REQUIRES: python

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.9.4.1
ARCH=noarch
BUILD=1tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/Pyrex-$VERSION.tar.gz
cd Pyrex-$VERSION
chown -R root.root .
python setup.py install --root=$PKG 
rm -fv $PKG/usr/info/dir
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  INSTALL.txt README.txt \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/Pyrex-$VERSION
  rm -rf $PKG
fi
