#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://www.linuxpowertop.org/download/powertop-1.2.tar.gz
# MD5SUMS: 4420482fff4c3f0c63a4a3cec56f2931 powertop-1.1.tar.gz
# MD5SUMS: fa18e6115e75417bf94ca38021f8959d powertop-1.2.tar.gz

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.2
ARCH=${ARCH:-i486}
BUILD=1tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/powertop-$VERSION.tar.gz
cd powertop-$VERSION
chown -R root.root .
make
make install DESTDIR=$PKG
mkdir -p $PKG/usr/man/man1
install -m 644 powertop.1 $PKG/usr/man/man1/
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/ || true
mv $PKG/usr/share/doc $PKG/usr/ || true
mv $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  COPYING Changelog README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/powertop-$VERSION
  rm -rf $PKG
fi
