#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://transcode.kabewm.com/transcode-1.0.4.tar.bz2
# MD5SUMS: e353c0ab7e927a8672528e05a9ae960b transcode-1.0.2.tar.gz
# MD5SUMS: 6f05b9efb8d67540dd6dbb7b8db47504 transcode-1.0.4.tar.bz2
# REQUIRES: a52dec ffmpeg gtk+ imagemagick libdv libdvdread libfame
# REQUIRES: libogg libpng libquicktime libtheora libvorbis libxml2
# REQUIRES: mjpegtools sdl x11
# OPTIONAL: gcc-g++ libXv

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.0.4
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/transcode-$VERSION.tar.bz2
cd transcode-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --docdir=/usr/doc/$NAME-$VERSION \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --program-prefix="" \
  --enable-shared \
  --disable-schemas-install \
  --with-libavcodec-includes=/usr/include/ffmpeg \
  --with-libpostproc-includes=/usr/include/postproc \
  --enable-mjpegtools \
  --enable-libpostproc \
  --enable-ogg \
  --enable-vorbis \
  --enable-theora \
  --enable-libdv \
  --enable-libquicktime \
  --enable-a52 \
  --enable-libxml2 \
  --enable-sdl \
  --enable-gtk \
  --enable-libfame \
  --enable-imagemagick \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
mkdir -p $PKG/usr/doc
mv $PKG/usr/share/doc/transcode $PKG/usr/doc/transcode-$VERSION
rmdir $PKG/usr/share/doc
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL README README-1.0.1 TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/transcode-$VERSION
  rm -rf $PKG
fi

exit $?

# This chunk has been added by autoport, part of portpkg.berlios.de:

#+configure-opts
  --with-libavcodec-includes=/usr/include/ffmpeg \
  --with-libpostproc-includes=/usr/include/postproc \
  --enable-mjpegtools \
  --enable-libpostproc \
  --enable-ogg \
  --enable-vorbis \
  --enable-theora \
  --enable-libdv \
  --enable-libquicktime \
  --enable-a52 \
  --enable-libxml2 \
  --enable-sdl \
  --enable-gtk \
  --enable-libfame \
  --enable-imagemagick \
#+configure-opts
#+install
mkdir -p $PKG/usr/doc
mv $PKG/usr/share/doc/transcode $PKG/usr/doc/transcode-$VERSION
rmdir $PKG/usr/share/doc
#+install
