#!/bin/sh
#
# SlackBuild for aalib
#
##################################
## Creator: Stefano Stabellini  ##
## stefano@stabellini.net       ##
## http://www.stabellini.net    ##
##################################
#

CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
PKG=/tmp/package-aalib

VERSION=1.2
ARCH=${ARCH:-i486}
BUILD=1stb

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG
echo "+=====================+"
echo "| aalib-$VERSION |"
echo "+=====================+"
cd $TMP
rm -rf aalib-$VERSION
tar xvzf $CWD/aalib-$VERSION.tar.gz
cd aalib-$VERSION
chown -R root.root .
find . -perm 777 -exec chmod 755 {} \;
find . -perm 775 -exec chmod 755 {} \;
find . -perm 700 -exec chmod 755 {} \;
find . -perm 744 -exec chmod 755 {} \;
find . -perm 666 -exec chmod 644 {} \;
find . -perm 664 -exec chmod 644 {} \;
find . -perm 600 -exec chmod 644 {} \;
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure --prefix=$PKG/usr --sysconfdir=/etc --localstatedir=/var/lib
make
make install DESTDIR=$PKG
chown -R root.bin $PKG/usr/bin
chown -R root.bin $PKG/usr/sbin
gzip -9 $PKG/usr/man/man3/*
gzip -9 $PKG/usr/man/cat8/*
gzip -9 $PKG/usr/man/man8/*
mkdir -p $PKG/usr/doc/aalib-$VERSION
cp AUTHORS $PKG/usr/doc/aalib-$VERSION
cp ANNOUNCE $PKG/usr/doc/aalib-$VERSION
cp COPYING $PKG/usr/doc/aalib-$VERSION
cp NEWS $PKG/usr/doc/aalib-$VERSION
cp README $PKG/usr/doc/aalib-$VERSION
cp INSTALL $PKG/usr/doc/aalib-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cd $PKG
makepkg -l y -c n ../aalib-$VERSION-$ARCH-$BUILD.tgz

