#!/bin/sh
# MAINTAINER: Piotr Simon 'sjn' <sajmon@tenboard.com>
# SOURCES: http://osdn.dl.sourceforge.net/sourceforge/slackins/slackins-3.0.tar.gz
# MD5SUMS: 9d2f62a3377582ce3494c2647939f81f slackins-3.0.tar.gz
# REQUIRES: desktop-file-utils gcc-g++ libXcursor libXft libXinerama libXmu libXrandr libmng libpng mesa
VERSION=3.0
ARCH=${ARCH:-i486}
BUILD=2sjn

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

cd /tmp || exit 1
tar xzvf $CWD/$NAME-$VERSION.tar.gz
cd $NAME-$VERSION || exit 1
chown -R root.root .
mkdir -p $PKG/usr/bin
mkdir -p $PKG/usr/share/pixmaps
mkdir -p $PKG/opt/kde/share/applnk/Utilities
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure $ARCH-slackware-linux || exit 1
make || exit 1 
make DESTDIR=$PKG install || exit 1

find $PKG/ -type d -name bin -o -name sbin | xargs -r chown -R root.bin

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)


mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL \
  $PKG/usr/doc/$NAME-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cd $PKG
rm -rf usr/lib

makepkg -l y -c n /tmp/$NAME-$VERSION-$ARCH-$BUILD.tgz
