#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://www.sacredchao.net/~piman/software/quodlibet-0.24.tar.gz
# MD5SUMS: d264fad1ac630a91bb8d69cb0a4c9d82 quodlibet-0.22.tar.gz
# MD5SUMS: 39718994ee234d0c442d9db330d7445a quodlibet-0.24.tar.gz
# REQUIRES: ctypes gst-python gtk+2 mutagen pygtk pyid3lib python
# OPTIONAL: desktop-file-utils pyao pyflac pygobject pymad pymodplug pymusepack pyvorbis

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.24
ARCH=${ARCH:-i486}
BUILD=1tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/quodlibet-$VERSION.tar.gz
cd quodlibet-$VERSION
chown -R root.root .
make extensions
make install PREFIX=/usr DESTDIR=$PKG
#install -m 644 quodlibet.desktop.in $PKG/usr/share/applications/quodlibet.desktop
find $PKG/ -name perllocal.pod | xargs -r rm -fv
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  COPYING HACKING NEWS README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/quodlibet-$VERSION
  rm -rf $PKG
fi
