#!/bin/sh
# MAINTAINER: Piotr Simon 'sjn' <sajmon@tenboard.com>
# SOURCES: http://www4.mplayerhq.hu/MPlayer/releases/codecs/essential-20060611.tar.bz2
# MD5SUMS: 26ec3f9feed5f89814b2ec5f436e937b  essential-20060611.tar.bz2
# MD5SUMS: 93f14fc57bc3bdd3ed047bfab39943fc  essential-20060501.tar.bz2
# MD5SUMS: 5fe89bb095bdf9b4f9cda5479dbde906  essential-20050412.tar.bz2
# REQUIRES: glibc
# OPTIONAL: cxxlibs
TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=20060611
ARCH=i386
BUILD=1sjn

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/essential-$VERSION.tar.bz2
cd essential-$VERSION
chown -R root.root .
#=install
mkdir -p $PKG/usr/lib/codecs
install -m 644 * $PKG/usr/lib/codecs/
#=install
rm -rfv $PKG/usr/info/dir
find $PKG/usr/share/mime/ -empty -exec rm -v {} \; || true
chown -R root.bin $PKG/{usr/X11R6/bin,{,usr/}{,s}bin} || true
#-strip
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
gzip -9 $PKG/usr/{info,man/{,*/}man?}/* || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f -exec chmod 644 {} \;
find $PKG/usr/doc -type d -exec chmod 755 {} \;
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/essential-$VERSION
  rm -rf $PKG
fi
