#!/bin/sh
# MAINTAINER: D.Riaux 'ldv' <ldv@no-log.org>
# SOURCES: http://www.physik.uni-wuerzburg.de/~vrbehr/cups-pdf/src/cups-pdf_2.4.1.tar.gz
# MD5SUMS: 4cef6dd76d09dc2f7f3df133ef339b52 cups-pdf_2.4.1.tar.gz
# REQUIRES: cups

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.4.1
ARCH=${ARCH:-i486}
BUILD=1ldv

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/cups-pdf_$VERSION.tar.gz
cd cups-pdf-$VERSION
chown -R root.root .
#-config

#=install
CFLAGS=$SLKCFLAGS
gcc $CFLAGS -o cups-pdf -Isrc src/cups-pdf.c
install -D -m 0755 cups-pdf $PKG/usr/lib/cups/backend/cups-pdf

# ppd files
mkdir -p $PKG/usr/share/cups/model
gunzip -f extra/*.ppd.gz
install -m 0644 extra/*.ppd $PKG/usr/share/cups/model
# default : rev4
( cd $PKG/usr/share/cups/model
    ln -sf PostscriptColor_rev4.ppd PostscriptColor.ppd
)

# config file
install -D -m 0644 extra/cups-pdf.conf $PKG/etc/cups/cups-pdf.conf.new
#=install

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  COPYING ChangeLog README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
#+tail
cat > $PKG/install/doinst.sh << EOF
config() {
    NEW="\$1"
    OLD="\`dirname \$NEW\`/\`basename \$NEW .new\`"
    if test ! -r \$OLD ; then
        mv \$NEW \$OLD
    elif cmp -s \$NEW \$OLD ; then
        rm \$NEW
    fi
}
config etc/cups/cups-pdf.conf.new
EOF
#+tail

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/cups-pdf-$VERSION
  rm -rf $PKG
fi
