#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://downloads.sourceforge.net/gdvdshrink/gDVDshrink-0.3-9.tgz
# MD5SUMS: 17a0d07bdf22d8793d75779561be509c gDVDshrink-0.3-9.tgz
# REQUIRES: dvdauthor gtk2-gladexml-perl gtk2-perl lsdvd perl
# OPTIONAL: desktop-file-utils mplayer

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.3-9
ARCH=${ARCH:-i486}
BUILD=1tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
rm -rf $NAME-$VERSION
mkdir -p $NAME-$VERSION
cd $NAME-$VERSION
tar xzvf $CWD/gDVDshrink-$VERSION.tgz
chown -R root.root .
mv usr/local/bin usr/
rmdir usr/local
mkdir -p usr/doc/gdvdshrink-$VERSION
mv opt/gDVDshrink/CHANGES opt/gDVDshrink/COPYING opt/gDVDshrink/INSTALL \
  opt/gDVDshrink/README opt/gDVDshrink/TODO usr/doc/gdvdshrink-$VERSION/
mkdir -p usr/share/applications
install -m 644 $CWD/gdvdshrink.desktop usr/share/applications/
find -type d | xargs -i mkdir -p $PKG/{}
find -type f | xargs -i install -m 644 {} $PKG/{}
chmod +x $PKG/usr/bin/* $PKG/opt/gDVDshrink/*.pl
find $PKG/ -name perllocal.pod | xargs -r rm -fv
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/%srcdirprefix%
  rm -rf $PKG
fi
