#!/bin/sh
# MAINTAINER: D.Riaux 'ldv' <ldv@no-log.org>
# SOURCES: http://dl.sourceforge.net/sourceforge/rox/rox-filer-2.5.tar.bz2
# MD5SUMS: 56e6a29f2dbdf11d6f4b74a3f03ff959 rox-filer-2.5.tar.bz2
# REQUIRES: gtk+2 libxml2 shared-mime-info x11

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.5
ARCH=${ARCH:-i486}
BUILD=1ldv

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/rox-filer-$VERSION.tar.bz2
cd rox-filer-$VERSION
chown -R root.root .

#-config

#=install
ROXAPPDIR="/usr/lib/rox"
MIMEINFODIR="/usr/share/mime/packages"
CHOICESDIR="/etc/xdg/rox.sourceforge.net"

./ROX-Filer/AppRun --compile

install -d "$PKG$ROXAPPDIR"
cp -ra ROX-Filer "$PKG$ROXAPPDIR"
rm -r $PKG$ROXAPPDIR/ROX-Filer/{build,src,*.dbg}

cat > "rox" << EOF
exec $ROXAPPDIR/ROX-Filer/AppRun "\$@"
EOF
install -D -m 0755 "rox" "$PKG/usr/bin/rox"

( cd Choices
    for _file in MIME-types/* ; do
        install -D -m 0755 $_file $PKG/$CHOICESDIR/$_file
    done
)

install -D -m 0644 rox.xml $PKG/$MIMEINFODIR/rox.xml

install -D -m 0644 rox.1 $PKG/usr/man/man1/rox.1
#=install

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  README README-es \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
#+doc
cp -a \
  ROX-Filer/Help/* \
  $PKG/usr/doc/$NAME-$VERSION/
#+doc
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

#+tail
cat > $PKG/install/doinst.sh <<EOF
if [ -x usr/bin/update-mime-database ]; then
   usr/bin/update-mime-database /usr/share/mime >/dev/null 2>&1
fi
EOF
#+tail

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/rox-filer-$VERSION
  rm -rf $PKG
fi
