#!/bin/sh
# MAINTAINER: Johannes Weiner 'hnaz' <hnazfoo at googlemail dot com>
# MAINTAINER: Piotr Simon 'sjn' <sajmon@users.berlios.de>
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://ftp.gnome.org/pub/gnome/sources/pango/1.21/pango-1.21.0.tar.bz2
# MD5SUMS: c75489ec7f5fe77e31e4cbde71ad0c16 pango-1.10.0.tar.bz2
# MD5SUMS: 86c3e08169a18200e64a0c5ee1be7fd9 pango-1.12.0.tar.bz2
# MD5SUMS: 10ddfbc43cf895639b77788ca637409c pango-1.12.1.tar.bz2
# MD5SUMS: f41488236baf881a4844216ac61abc24 pango-1.12.2.tar.bz2
# MD5SUMS: 8ea80c1d747a2844d7d096bfd347c2dc pango-1.16.2.tar.bz2
# MD5SUMS: 81efeac639977ed3f56c82f16ee0be74 pango-1.18.2.tar.bz2
# MD5SUMS: 4a9862b5151f16dcad8e30dd6ef08549 pango-1.18.3.tar.bz2
# MD5SUMS: d993288b0704f60b109cd2ca44423e7a pango-1.21.0.tar.bz2
# REQUIRES: cairo glib2 x11 x11-devel
# OPTIONAL: gtk-doc libXft libxcb linuxdoc-tools

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.21.0
ARCH=${ARCH:-i486}
BUILD=1sjn

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/pango-$VERSION.tar.bz2
cd pango-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --docdir=/usr/doc/$NAME-$VERSION \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --program-prefix="" \
  --enable-shared \
  --disable-schemas-install \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog HACKING INSTALL NEWS README README.win32 THANKS \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
cp -a $TMP/pango-$VERSION/modules/pango.modules etc/pango/
sed -i "s,^#$,# ModulesPath \= \/usr\/lib\/pango\/$VERSION\/modules,g;s,\/tmp,\/usr\/lib,g" etc/pango/pango.modules

makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/pango-$VERSION
  rm -rf $PKG
fi
