#!/bin/sh
# MAINTAINER: Vadim Shevchenko 'shv' <shevadim@mail.ru>
# SOURCES: http://distfiles.atheme.org/audacious-plugins-1.4.4.tgz
# MD5SUMS: 520187b4840c534001604195ce603ed9 audacious-plugins-1.3.3.tgz
# MD5SUMS: 417ffe1cae7081b0dec404b659a6d67e audacious-plugins-1.3.4.tgz
# MD5SUMS: dc1374344cfde2667b2650fdb4227b78 audacious-plugins-1.4.4.tgz
# REQUIRES: audacious curl esound glib2 gtk+2 lame libmad libxml2 sdl
# REQUIRES: taglib dbus-glib imlib2 libXcomposite 
# OPTIONAL: arts libcdio libmpcdec
# OPTIONAL: libmtp libogg libsndfile libvorbis wavpack

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.4.4
ARCH=${ARCH:-i486}
BUILD=1shv

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/audacious-plugins-$VERSION.tgz
cd audacious-plugins-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL NEWS \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/audacious-plugins-$VERSION
  rm -rf $PKG
fi
