#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://dl.sourceforge.net/wxpython/wxPython-src-2.6.2.1.tar.gz
# MD5SUMS: 6cb6517546e983e3d730708e0de0ed10 wxPython-src-2.6.0.0.tar.gz
# MD5SUMS: aae333c806acd5e5227a7afd2505286a wxPython-src-2.6.2.1.tar.gz
# MD5SUMS: 8d7da3a498573cf6dc8d2d445c6d20d5 wxPython-src-2.8.1.1.tar.bz2
# REQUIRES: libxml2 pygtk python wxgtk

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.6.2.1
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/wxPython-src-$VERSION.tar.gz
cd wxPython-src-$VERSION
chown -R root.root .
cd wxPython
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
python ./setup.py \
  WX_CONFIG=/usr/bin/wx-config \
  WXPORT=gtk2 \
  UNICODE=1 \
  BUILD_GLCANVAS=0 \
  BUILD_OGL=0 \
  BUILD_STC=1 \
  BUILD_GIZMOS=1 \
  build install --root=$PKG
rm -fv $PKG/usr/info/dir
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  docs/* \
  $PKG/usr/doc/$NAME-$VERSION
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/wxGTK-$VERSION
  rm -rf $PKG
fi
