#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://fpdownload.macromedia.com/get/shockwave/flash/english/linux/9.0.31.0/install_flash_player_9_linux.tar.gz
# MD5SUMS: 76b38231a68995935185aa42dfda9db7 install_flash_player_9_linux.tar.gz
# REQUIRES: gtk+2 x11
# OPTIONAL: mozilla-firefox seamonkey

VERSION=9
ARCH=i386
BUILD=1tom

CWD=`pwd`
NAME=`basename $CWD`
PKG=/tmp/package-flash-plugin
rm -rf $PKG
mkdir -p $PKG/usr

cd /tmp
tar xzvf $CWD/install_flash_player_9_linux.tar.gz
cd install_flash_player_9_linux
chown -R root.root .
pkg-config --exists firefox-plugin && LIBDIR=`pkg-config --variable libdir firefox-plugin`
pkg-config --exists seamonkey-plugin && LIBDIR=`pkg-config --variable libdir seamonkey-plugin`
if ! [ "${LIBDIR:-}" ]; then
  echo "*** Either Firefox or Seamonkey is needed for Flash-player!"
  exit 1
fi
mkdir -p $PKG$LIBDIR/plugins $PKG$LIBDIR/components
mv *.so $PKG$LIBDIR/plugins/
mv *.xpt $PKG$LIBDIR/components/
mkdir -p $PKG/usr/doc/flash-plugin-$VERSION
cp -a \
  Readme.* \
  $PKG/usr/doc/flash-plugin-$VERSION

cd $PKG
mkdir -p $PKG/install
cat $CWD/slack-desc >install/slack-desc
find | xargs file | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded
makepkg -p -l y -c n /tmp/$NAME-$VERSION-$ARCH-$BUILD.tgz
