#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://download.berlios.de/sonata/sonata-1.3.tar.bz2
# MD5SUMS: 8b05424b9f3086e72b9dfd45770c229d sonata-1.3.tar.bz2
# REQUIRES: dbus-python desktop-file-utils gtk+2 python

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.3
ARCH=noarch
BUILD=1tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/sonata-$VERSION.tar.bz2
cd sonata-$VERSION
chown -R root.root .
python setup.py build install --root=$PKG
mv $PKG/usr/share/man $PKG/usr/ || true
mv $PKG/usr/share/doc $PKG/usr/ || true
mv $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  CHANGELOG COPYING README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/sonata-$VERSION
  rm -rf $PKG
fi
