#!/bin/sh
# MAINTAINER: Piotr Simon 'sjn' <sajmon@tenboard.com>
# SOURCES: http://www.rarlab.com/rar/unrarsrc-3.7.6.tar.gz
# MD5SUMS: 4e8b975374064b774ea80067e11ccf13 unrarsrc-3.5.3.tar.gz
# MD5SUMS: e6d9e4997da6796ddc5344e995a621e6 unrarsrc-3.6.1.tar.gz
# MD5SUMS: 10b142866c656e40273434aae6747f96 unrarsrc-3.7.5.tar.gz
# MD5SUMS: c6e1ae41bc140d47f4608c1ab5f01802 unrarsrc-3.7.6.tar.gz
# REQUIRES: gcc-g++

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=3.7.6
ARCH=${ARCH:-i486}
BUILD=1sjn

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr/bin
cd $TMP || exit 1
tar xzvf $CWD/${NAME}src-${VERSION}.tar.gz || exit 1
cd $NAME || exit 1
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
make -f makefile.unix CXXFLAGS="$SLKCFLAGS" || exit 1
cp unrar $PKG/usr/bin
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp {license,readme}.txt $PKG/usr/doc/$NAME-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG || exit 1
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/$NAME
  rm -rf $PKG
fi
