#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://ftp.gnome.org/pub/gnome/sources/epiphany-extensions/2.14/epiphany-extensions-2.14.1.1.tar.bz2
# MD5SUMS: 3e807a83f068e41ce34c3c653a3353b6 epiphany-extensions-2.14.1.1.tar.bz2
# REQUIRES: epiphany pcre
# OPTIONAL: deskbar-applet gcc-g++ linuxdoc-tools scrollkeeper
## MD5SUMS: 1b8ec450167010b25bba48295b5808cf epiphany-extensions-2.14.1.1.tar.bz2

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.14.1.1
ARCH=${ARCH:-i486}
BUILD=3tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/epiphany-extensions-$VERSION.tar.bz2
cd epiphany-extensions-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  --disable-static \
  --disable-scrollkeeper \
  --with-extensions=all,adblock \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
rm -rf $PKG/var/lib/scrollkeeper
rm -fv $PKG/usr/info/dir
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING COPYING.README ChangeLog HACKING NEWS README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/epiphany-extensions-$VERSION
  rm -rf $PKG
fi
