#!/bin/sh
# MAINTAINER: Piotr Simon 'sjn' <sajmon@tenboard.com>
# MAINTAINER: Piotr Simon 'sjn' <sajmon@users.berlios.de>
# SOURCES: http://cairographics.org/releases/cairo-1.6.0.tar.gz
# MD5SUMS: f0ff35c91983b7bf226154e68b280be3 cairo-1.0.0.tar.gz
# MD5SUMS: d0b7111a14f90ec3afa777ec40c44984 cairo-1.0.2.tar.gz
# MD5SUMS: 9002b0e69b3f94831a22d3f2a7735ce2 cairo-1.0.4.tar.gz
# MD5SUMS: 2460487b1257a5583c889b1b9d2033ec cairo-1.2.2.tar.gz
# MD5SUMS: 6890023ac2c6304c284fae5d56768a17 cairo-1.6.0.tar.gz
# REQUIRES: expat libpng pixman x11 x11-devel zlib
# OPTIONAL: fontconfig gcc-g++ libXrender
TMP=${TMP:-/var/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.6.0
ARCH=${ARCH:-i486}
BUILD=2sjn

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP || exit 1
rm -rf $NAME-$VERSION
tar xzvf $CWD/$NAME-$VERSION.tar.gz || exit 1
cd $NAME-$VERSION || exit 1
chown -R root.root .
find . -perm 777 -exec chmod 755 {} \;
find . -perm 664 -exec chmod 644 {} \;
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --mandir=/usr/man \
  --sysconfdir=/etc \
  --enable-warnings \
  --disable-atsui \
  --disable-gtk-doc \
  --disable-glitz \
  --disable-quartz \
  --disable-static \
  --disable-win32 \
  --disable-xcb \
  $ARCH-slackware-linux || exit 1
make || exit 1
make install DESTDIR=$PKG || exit 1
rm -rf $PKG/usr/info/dir
#find $PKG/ -type d -name bin -o -name sbin | xargs -r chown -R root.bin
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  #find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
#mv $PKG/usr/share/{man,doc} $PKG/usr/
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog NEWS README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
( cd $PKG/usr/doc/cairo-$VERSION ; ln -sf /usr/share/gtk-doc/html/cairo html )
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG || exit 1
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/$NAME-$VERSION
  rm -rf $PKG
fi
