#!/bin/sh
# MAINTAINER: Vadim Shevchenko 'shv' <shevadim@mail.ru>
# SOURCES: http://downloads.xiph.org/releases/vorbis/libvorbis-1.2.0.tar.gz
# MD5SUMS: 478646358c49f34aedcce58948793619 libvorbis-1.2.0.tar.gz
# REQUIRES: libogg

# This build script is highly based on the script from the Slackware 12.0


TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.2.0
ARCH=${ARCH:-i486}
BUILD=1shv

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG
cd /tmp
rm -rf libvorbis-$VERSION
tar xzvf $CWD/libvorbis-$VERSION.tar.gz || exit 1
cd libvorbis-$VERSION
chown -R root:root .
find . -perm 777 -exec chmod 755 {} \;
find . -perm 664 -exec chmod 644 {} \;
./configure \
  --prefix=/usr \
  --build=$ARCH-slackware-linux
make || exit 1
make install DESTDIR=$PKG
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
mv $PKG/usr/share/doc $PKG/usr
cp -a \
  AUTHORS COPYING HACKING README \
  $PKG/usr/doc/libvorbis-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/libvorbis-$VERSION
  rm -rf $PKG
fi
