#!/bin/sh
# MAINTAINER: Daniel Kmieæ 'dan' <danielos@narsil.asua.org.pl>
# SOURCES: http://switch.dl.sourceforge.net/sourceforge/ri-li/Ri-li-1.0.3.tar.bz2
# MD5SUMS: 36f39cf5966fa4bb495eccf69bb87da6 Ri-li-1.0.3.tar.bz2
# REQUIRES: cxxlibs gcc-g++ sdl

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.0.3
ARCH=${ARCH:-i486}
BUILD=1dan

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/Ri-li-$VERSION.tar.bz2
cd Ri-li-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
# make extra link with lowercase letters
( cd $PKG/usr/bin
   ln -s Ri_li ri_li
)

# remove gentoo ebuild; who will use it on slackware ?
( cd $PKG/usr/share/Ri-li
   rm -f Ri-li-${VERSION}*.ebuild
)

rm -rf $PKG/usr/info/dir
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog NEWS README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/Ri-li-$VERSION
  rm -rf $PKG
fi
