#!/bin/sh
# MAINTAINER: Piotr Simon 'sjn' <sajmon@tenboard.com>
# SOURCES: http://downloads.sourceforge.net/sylpheed-claws/claws-mail-extra-plugins-3.1.0.tar.bz2
# MD5SUMS: 1dc867cb2b781a65eace390fd1deb424 claws-mail-extra-plugins-2.10.0.tar.bz2
# MD5SUMS: 30fa4df35a55fbbc584ce40d7145f92e claws-mail-extra-plugins-2.8.0.tar.bz2
# MD5SUMS: 5e86ceebdc36c3218cccd718de8b30af claws-mail-extra-plugins-2.9.0.tar.bz2
# MD5SUMS: cde3849c15009521b51c4afc94f1606a claws-mail-extra-plugins-2.9.1.tar.bz2
# MD5SUMS: c35851d15f9000fd77c87be898d90984 claws-mail-extra-plugins-2.9.2.tar.bz2
# MD5SUMS: c59f022987fb8136b6d4a8a0611d2d39 claws-mail-extra-plugins-3.0.0.tar.bz2
# MD5SUMS: 7dd8ee1d759d5017ebb673be71df9357 claws-mail-extra-plugins-3.0.1.tar.bz2
# MD5SUMS: 2385b7cd48d13de37bb3450688384d96 claws-mail-extra-plugins-3.1.0.tar.bz2
# MD5SUMS: 06b53d69913ea1c96fb154fa2686606a sylpheed-claws-extra-plugins-2.3.0.tar.bz2
# MD5SUMS: f0a7c85c033dba930706f18b73274213 sylpheed-claws-extra-plugins-2.4.0.tar.bz2
# MD5SUMS: db771d49bf9bde1cce075b93f8028a19 sylpheed-claws-extra-plugins-2.5.2.tar.bz2
# REQUIRES: curl db44 gpgme libetpan libgtkhtml
# OPTIONAL: poppler

TMP=${TMP:-/var/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=3.1.0
ARCH=${ARCH:-i486}
BUILD=1sjn

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
rm -rf $NAME-$VERSION
tar xjvf $CWD/$NAME-$VERSION.tar.bz2
cd $NAME-$VERSION
mkdir -p $PKG/usr/doc/$NAME-$VERSION
mv README $PKG/usr/doc/$NAME-$VERSION/
chown -R root.root .

for i in *;do
( cd $i
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  --disable-static \
  $ARCH-slackware-linux || exit 1
make || exit 1
make install DESTDIR=$PKG
)
done
rm -rf $PKG/usr/info/dir
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true

find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
chown -R root.root .
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/$NAME-$VERSION
  rm -rf $PKG
fi
