#!/bin/sh
# MAINTAINER: Johannes Weiner 'hnaz' <hnazfoo at googlemail dot com>
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: ftp://ftp.gnome.org/pub/GNOME/sources/glib/2.12/glib-2.12.3.tar.bz2
# SOURCES: ftp://ftp.gnome.org/pub/GNOME/sources/glib/2.12/glib-2.12.3.tar.bz2
# MD5SUMS: 60c9f62979415bcb82f0b87d6785dc3b glib-2.10.0.tar.bz2
# MD5SUMS: 51df7932da118f7f27bbda82b65f0f91 glib-2.10.1.tar.bz2
# MD5SUMS: 718961161ee1692c216a2d542196a04a glib-2.10.2.tar.bz2
# MD5SUMS: cbf663f8bc733e2f6c90599942f6616a glib-2.12.3.tar.bz2
# MD5SUMS: 803305bfd59cf7421d90983bf63e5227 glib-2.8.0.tar.bz2
# MD5SUMS: 2ba1146e767454e14ac0788187c35892 glib-2.9.6.tar.bz2
# REQUIRES: pkgconfig
# OPTIONAL: gtk-doc sgml-tools

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.12.3
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/glib-$VERSION.tar.bz2
cd glib-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  --disable-static \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
rm -fv $PKG/usr/info/dir
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL INSTALL.in NEWS README README.in README.win32 \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/glib-$VERSION
  rm -rf $PKG
fi
