#!/bin/sh
#
# SlackBuild for snort
#
##################################
## Creator: Stefano Stabellini  ##
## stefano@stabellini.net       ##
## http://www.stabellini.net    ##
##################################
#

CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
PKG=/tmp/package-snort

VERSION=2.3.1
ARCH=${ARCH:-i486}
BUILD=1stb

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG
echo "+================+"
echo "| snort-$VERSION |"
echo "+================+"
cd $TMP
rm -rf snort-$VERSION
tar xvzf $CWD/snort-$VERSION.tar.gz
cd snort-$VERSION
chown -R root.root .
find . -perm 777 -exec chmod 755 {} \;
find . -perm 775 -exec chmod 755 {} \;
find . -perm 700 -exec chmod 755 {} \;
find . -perm 744 -exec chmod 755 {} \;
find . -perm 666 -exec chmod 644 {} \;
find . -perm 664 -exec chmod 644 {} \;
find . -perm 600 -exec chmod 644 {} \;
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure --prefix=/usr --localstatedir=/var/lib
make
make install DESTDIR=$PKG
mkdir -p $PKG/var/log/snort
mkdir -p $PKG/etc/rules
cp $CWD/*.config.new $PKG/etc
cp $CWD/*.conf.new $PKG/etc
cp $CWD/*.map.new $PKG/etc
#cp -R $CWD/rules $PKG/etc
tar xpjvf $CWD/rules.tar.bz2 -C $PKG/etc
cp $CWD/sid.new $PKG/etc
cp $CWD/generators.new $PKG/etc
strip $PKG/usr/bin/*
chown -R root.bin $PKG/usr/bin
gzip -9 $PKG/usr/man/man8/*
mkdir -p $PKG/usr/doc/snort-$VERSION
cp RELEASE.NOTES $PKG/usr/doc/snort-$VERSION
cp COPYING $PKG/usr/doc/snort-$VERSION
cp LICENSE $PKG/usr/doc/snort-$VERSION
cp doc/* $PKG/usr/doc/snort-$VERSION
cp ChangeLog $PKG/usr/doc/snort-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh
cd $PKG
makepkg -l y -c n ../snort-$VERSION-$ARCH-$BUILD.tgz

