#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://www.winki-the-ripper.de/share/dist/winki-0.4.1.tar.gz
# MD5SUMS: 3a1e177622d7002cb4cb1e92c677d754 winki-0.4.1.tar.gz
# REQUIRES: pygtk python
# OPTIONAL: dvdauthor ffmpeg lame libdvdcss lsdvd mjpegtools mplayer vcdimager vorbis-tools

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.4.1
ARCH=noarch
BUILD=2tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/winki-$VERSION.tar.gz
cd winki-$VERSION
chown -R root.root .
python setup.py build install --root=$PKG
rm -rf $PKG/usr/lib/perl?/?.?.?/*-linux/perllocal.pod
rm -rf $PKG/var/lib/scrollkeeper
rm -rf $PKG/usr/info/dir
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  $PKG/usr/share/winkirip/doc/* \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/winki-$VERSION
  rm -rf $PKG
fi
