#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://www.sacredchao.net/~piman/software/mutagen-1.9.tar.gz
# MD5SUMS: 9ce5d5f14e02f2eabd919d6bdaebadbc mutagen-1.5.1.tar.gz
# MD5SUMS: 96394da027fb447cf37fa2b3aac0325d mutagen-1.9.tar.gz
# REQUIRES: python

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=1.9
ARCH=noarch
BUILD=1tom

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/mutagen-$VERSION.tar.gz
cd mutagen-$VERSION
chown -R root.root .
python setup.py build install --root=$PKG
find $PKG/ -name perllocal.pod | xargs -r rm -fv
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  COPYING NEWS README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/mutagen-$VERSION
  rm -rf $PKG
fi
