#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# MAINTAINER: Tomas Stefano 'lem' <stefano at cedo dot cz>
# SOURCES: ftp://oss.codepoet.no/revelation/revelation-0.4.11.tar.bz2
# MD5SUMS: d00dd223a1c35472e573fb11d758cd98 revelation-0.4.0.tar.bz2
# MD5SUMS: e2db4a2f00f59b18798d4453c778129f revelation-0.4.11.tar.bz2
# REQUIRES: atk cracklib expat gconf glib2 gnome-keyring gnome-vfs gtk+2 libart_lgpl libbonobo libbonoboui libgnome libgnomecanvas libgnomeui libjpeg libxml2 openssl orbit2 pango popt pycrypto python x11 x11-devel zlib
# OPTIONAL: desktop-file-utils shared-mime-info

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.4.11
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xjvf $CWD/revelation-$VERSION.tar.bz2
cd revelation-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  --disable-mime-update \
  --disable-desktop-update \
  $ARCH-slackware-linux
make
GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 \
make install DESTDIR=$PKG
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog INSTALL NEWS README TODO \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh
( cd $PKG; find etc/gconf/schemas/ -name "*.schemas" ) | xargs -rl echo gconf >>$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/revelation-$VERSION
  rm -rf $PKG
fi
