#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://freedesktop.org/~david/dist/hal-0.5.7.tar.gz
# MD5SUMS: 4163afb8285db64e00e7b1392b401d92 hal-0.5.7.tar.gz
# REQUIRES: expat libusb python
# OPTIONAL: dbus dbus-bindings dbus-glib dbus-python pygobject

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.5.7
ARCH=${ARCH:-i486}
BUILD=10tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/$NAME-$VERSION.tar.gz
cd $NAME-$VERSION
chown -R root.root .
if grep -sq "2\.4" /usr/include/linux/version.h; then
  cat <<EOF
===========================================================================
HAL requires Linux kernel-headers version 2.6, but your system seems to
have version 2.4 installed. Upgrade to version 2.6 to build HAL!

NOTES:
 * This package is maybe located in extra/ or in testing/ of your Slackware
   distribution, but that in extra/ should be preferred.
 * If d/kernel-headers in your Slackware release is of version 2.4 it is
   recommended to DOWNGRADE to them after you have built HAL.
===========================================================================
EOF
  exit 1
fi
if pkg-config "dbus-1 > 0.62"; then
  echo "DBus > 0.62, patching HAL"
  cat $CWD/hal-0.5.7.1-fixes-1.patch | patch -p1 --verbose
fi
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  --disable-static \
  --with-pid-file=/var/run/hald.pid \
  --with-system-pid-file=/var/run/hald.pid \
  --with-hal-user=daemon \
  --with-hal-group=daemon \
  --enable-fstab-sync \
  --enable-hotplug-map \
  --enable-pcmcia-support \
  --enable-sysfs-carrier \
  --enable-doxygen-docs \
  --disable-docbook-docs \
  $ARCH-slackware-linux
make
make install DESTDIR=$PKG
mkdir $PKG/etc/rc.d
install -m 644 $CWD/rc.hal $PKG/etc/rc.d/
mv $PKG/etc/rc.d/rc.hal $PKG/etc/rc.d/rc.hal.new
sed -i "s,<policy at_console=\"true\">,<policy group=\"users\">," \
  $PKG/etc/dbus-1/system.d/*
rm -rf $PKG/usr/info/dir
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/{man,doc} $PKG/usr/ || true
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog HACKING NEWS README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/{man,info} -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc
cat $CWD/doinst.sh >$PKG/install/doinst.sh

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/$NAME-$VERSION
  rm -rf $PKG
fi
