#!/bin/sh
# MAINTAINER: Daniel Kmieæ 'dan' <danielos@narsil.asua.org.pl>
# MAINTAINER: Piotr Simon 'sjn' <sajmon@tenboard.com>
# SOURCES: http://downloads.sourceforge.net/kipi/kipi-plugins-0.1.4.tar.bz2
# MD5SUMS: 1dd0cb05e0c7da43861d2bf0affaa4b3 kipi-plugins-0.1.0-beta2.tar.bz2
# MD5SUMS: 7b8e55906b5d08280ab3ad3c2b43e8ab kipi-plugins-0.1.3.tar.bz2
# MD5SUMS: 62469960593284b62302bde75a898c46 kipi-plugins-0.1.4.tar.bz2
# REQUIRES: kdelibs libkipi
# OPTIONAL: desktop-file-utils imlib2 kdepim libgphoto2 libgpod libkdcraw libkexif libkexiv2 libtiff libxslt
VERSION=0.1.4
ARCH=${ARCH:-i486}
BUILD=1sjn

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME
rm -rf $PKG
mkdir -p $PKG/{install,usr/doc/$NAME-$VERSION}

cd $TMP || exit 1
rm -rf $NAME-$VERSION
tar xjvf $CWD/$NAME-$VERSION.tar.bz2 || exit 1
cd $NAME-$VERSION || exit 1
# apply patch for bad include of cropframe.h 
# in file kipi-plugins/printwizard/frmprintwizardbase.ui
patch -p1 < $CWD/frmprintwizard-cropframe.patch
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --program-prefix="" \
  --disable-static \
  $ARCH-slackware-linux || exit 1
make || exit 1
make install DESTDIR=$PKG || exit 1
cp -a \
  AUTHORS ChangeLog COPYING INSTALL README TODO \
  $PKG/usr/doc/$NAME-$VERSION/

cd $PKG || exit 1
cat $CWD/slack-desc >$PKG/install/slack-desc

find -type d | grep /doc/ | xargs -r chmod 755
find -type f | grep /doc/ | xargs -r chmod 644
find -type f | xargs file | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
find -type f | grep -e /man/ -e /info/ | xargs -r gzip -9

makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz
