#!/bin/sh
# MAINTAINER: Piotr Simon 'sjn' <sajmon@tenboard.com>
# SOURCES: http://www.libgd.org/releases/gd-2.0.34.tar.bz2
# MD5SUMS: be0a6d326cd8567e736fbc75df0a5c45 gd-2.0.33.tar.gz
# MD5SUMS: 8c25c322f12030b1c24488efd577fec0 gd-2.0.34.tar.bz2
# REQUIRES: fontconfig libXpm libjpeg libpng
TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.0.34
ARCH=${ARCH:-i486}
BUILD=2sjn

if [ "$ARCH" = "i386" ]; then
  OPTIMIZE="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  OPTIMIZE="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  OPTIMIZE="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  OPTIMIZE="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP || exit 1
rm -rf gd-$VERSION
tar xjvf $CWD/$NAME-$VERSION.tar.bz2 || exit 1
cd $NAME-$VERSION || exit 1
chown -R root.root .
CFLAGS="$OPTIMIZE" \
CXXFLAGS="$OPTIMIZE" \
./configure \
  --prefix=/usr \
  --program-prefix= \
  --program-suffix= \
  --disable-static \
  --build=$ARCH-slackware-linux || exit 1

make || exit 1
make install DESTDIR=$PKG || exit 1

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
)

mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  COPYING *.html README* *.png \
  $PKG/usr/doc/$NAME-$VERSION/

cd $PKG || exit 1
makepkg -p -l y -c n $TMP/$NAME-$VERSION-$ARCH-$BUILD.tgz
