#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://heanet.dl.sourceforge.net/gtk-server/gtk-server-2.2.1.tar.gz
# MD5SUMS: 3d8697d07c256be3629701f15ca91dbe gtk-server-2.0.12.tar.gz
# MD5SUMS: d02650037c1fb482d5bc8d4a753508b2 gtk-server-2.1.3.tar.gz
# MD5SUMS: 3d2006964b57c08c9fee4a8c5be80918 gtk-server-2.2.1.tar.gz
# REQUIRES: gtk+2 libffi
# OPTIONAL: libglade
# UP2DATE: http://heanet.dl.sourceforge.net/sourceforge/gtk-server

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=2.2.1
ARCH=${ARCH:-i486}
BUILD=1tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/gtk-server-$VERSION.tar.gz
cd gtk-server-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --docdir=/usr/doc/$NAME-$VERSION \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --program-prefix="" \
  --disable-schemas-install \
  --with-gtk2 \
  $ARCH-slackware-linux
make
mkdir $PKG/etc
make install prefix=$PKG/usr SYSCONFIG=$PKG/etc
rmdir $PKG/usr/etc
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  CREDITS INSTALL README.1ST \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gtk-server-$VERSION
  rm -rf $PKG
fi

exit $?

# This chunk has been added by autoport, part of portpkg.berlios.de:

#-ac_disable_static
#=install
make
mkdir $PKG/etc
make install prefix=$PKG/usr SYSCONFIG=$PKG/etc
rmdir $PKG/usr/etc
#=install
#+configure-opts
  --with-gtk2 \
#+configure-opts
