#!/bin/sh
# MAINTAINER: T. Pfaff 'tom' <topf@users.berlios.de>
# SOURCES: http://dbus.freedesktop.org/releases/dbus-0.62.tar.gz
# MD5SUMS: ba7692f63d0e9f1ef06703dff56cb650 dbus-0.62.tar.gz
# OPTIONAL: cxxlibs expat gcc-g++
# REQUIRES: dbus glib2 libxml2 pkgconfig x11
# FLAGS: no-fakeroot

TMP=${TMP:-/tmp}
CWD=`pwd`
NAME=`basename $CWD`
PKG=$TMP/package-$NAME

VERSION=0.62
ARCH=${ARCH:-i486}
BUILD=5tom

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

rm -rf $PKG
mkdir -p $PKG/usr
cd $TMP
tar xzvf $CWD/dbus-$VERSION.tar.gz
cd dbus-$VERSION
chown -R root.root .
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --program-prefix="" \
  --disable-static \
  --enable-x \
  --disable-gtk \
  --disable-mono \
  --disable-mono-docs \
  --disable-python \
  --disable-static \
  --disable-qt \
  --disable-tests \
  --enable-checks \
  --enable-asserts \
  --enable-glib \
  --with-system-pid-file=/var/run/dbus.pid \
  --with-session-socket-dir=/tmp \
  $ARCH-slackware-linux
( cd glib
  make
  make install DESTDIR=$PKG
)
mkdir -p $PKG/var/lib/dbus
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-debug
)
mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/share/info $PKG/usr/ || true
rm -fv $PKG/usr/info/dir
mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
  AUTHORS COPYING ChangeLog HACKING INSTALL NEWS README \
  $PKG/usr/doc/$NAME-$VERSION/
find $PKG/usr/doc -type f | xargs -r chmod 644
find $PKG/usr/doc -type d | xargs -r chmod 755
find $PKG/usr/man $PKG/usr/info -type f | xargs -r gzip -9
mkdir -p $PKG/install
cat $CWD/slack-desc >$PKG/install/slack-desc

cd $PKG
makepkg -p -l y -c n $TMP/$NAME-`echo $VERSION | tr - _`-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/dbus-$VERSION
  rm -rf $PKG
fi
